In [110]:
import pandas as pd
import dspy
import os
from dspy.evaluate import Evaluate
from dspy.evaluate.metrics import answer_exact_match

In [111]:
# Load the CSV dataset
df = pd.read_csv("shell_commands_dataset.csv")

In [112]:
df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)
# Convert to list of dictionaries
trainset_dict = df_shuffled.to_dict(orient='records')

# Split dataset (80% train, 20% test)
split_index = int(len(trainset_dict) * 0.9)
trainset = trainset_dict[:split_index]
testset = trainset_dict[split_index:]

# Create examples with 'answer' instead of 'command'
train_examples = [
    dspy.Example(natural_language_prompt=x["prompt"], MacOS_shell_command=x["command"]).with_inputs("natural_language_prompt")
    for x in trainset
]
test_examples = [
    dspy.Example(natural_language_prompt=x["prompt"], MacOS_shell_command=x["command"]).with_inputs("natural_language_prompt")
    for x in testset
]

In [113]:
# Updated Signature using 'answer'
# class resultantcommand(dspy.Signature):
#     """Generate shell commands from natural language prompts."""
#     question = dspy.InputField(desc="User's natural language prompt")
#     answer = dspy.OutputField(desc="shell commands required to fulfill user's request")

class CommandGenerator(dspy.Module):
    def __init__(self):
        super().__init__()
        self.generate = dspy.ChainOfThought("natural_language_prompt -> MacOS_shell_command")
    
    def forward(self, natural_language_prompt):
        return self.generate(natural_language_prompt=natural_language_prompt)

In [114]:
# Configuration (use environment variable for API key)
# lm = dspy.LM('openai/gpt-3.5-turbo', api_key='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')
# dspy.configure(lm=lm)


gemini = dspy.LM("gemini/gemini-1.5-pro",
                         api_key="AIzaSyDutlHakJqczH-p44CIJQY5ltNAOhv_2kY")
dspy.settings.configure(lm=gemini, max_tokens=1024)

In [115]:
class Assess(dspy.Signature):
    """Validate EVERY LINE of the command sequence for:
    1. Correctness for the task
    2. Valid shell syntax
    3. No human-language phrases (e.g., 'now go in')
    4. No redundant steps"""
    
    task = dspy.InputField(desc="User's original request")
    command_sequence = dspy.InputField(desc="Multi-line shell commands to validate line-by-line")
    validation = dspy.OutputField(
        desc=f"""Final verdict:
- YES only if ALL lines are valid shell commands relevant to the task
- NO if any line of command is invalid,is not an up-to-date MacOS command, does not implement all the required steps to do the task: "{task}" end-to-end, irrelevant, or contains non-commands"""
    )

def metric(task, prediction, trace=None):
    # Remove comments and empty lines
    command_sequence = prediction.MacOS_shell_command
    cleaned_commands = "\n".join([
        line.strip() for line in command_sequence.split('\n')
        if line.strip() and not line.strip().startswith('#')
    ])
    
    # Use ChainOfThought to force detailed validation
    judge = dspy.ChainOfThought(Assess)
    evaluation = judge(task=task, command_sequence=cleaned_commands)
    
    # Print the reasoning chain for debugging
    print(f"Validation Reasoning:\n{evaluation.validation}\n")
    
    is_valid = evaluation.validation.strip().upper() == "YES"
    return int(is_valid)

In [116]:
# Initialize and evaluate
generator = CommandGenerator()

#check if LM is working 
print(generator(natural_language_prompt="Hi"))

Prediction(
    reasoning="The prompt is a simple greeting.  There's no specific shell command implied.  A reasonable response is to simply echo the greeting.",
    MacOS_shell_command='echo "Hi"'
)

In [117]:
evaluator = Evaluate(
    devset=test_examples,
    metric=metric,  # Now works with default 'answer' field
    display_progress=True,
    display_table=60,
    num_threads=4,
    provide_traceback=True)

results = evaluator(generator)
print(f"\nEvaluation Results - Exact Match Accuracy: {results}")

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 14.00 / 16 (87.5%):  68%|██████▊   | 15/22 [00:00<00:00, 463.61it/s]

Average Metric: 18.00 / 22 (81.8%): 100%|██████████| 22/22 [00:00<00:00, 466.78it/s]

2025/05/01 02:10:11 INFO dspy.evaluate.evaluate: Average Metric: 18 / 22 (81.8%)

,natural_language_prompt,example_MacOS_shell_command,reasoning,pred_MacOS_shell_command,metric
0,Search for 'Deep Learning books' on Google using Safari,open -a Safari 'https://www.google.com/search?q=Deep+Learning+books',We can use the `open` command with the URL of the Google search to...,"open -a Safari ""https://www.google.com/search?q=Deep+Learning+books""",✔️ [1]
1,Create a new Python virtual environment,python3 -m venv myenv,"To create a new Python virtual environment, we can use the `venv` ...",python3 -m venv .venv,✔️ [1]
2,Check for system crashes,"log show --predicate 'eventMessage CONTAINS \crash\""' --style syslog""",We can use the `log show` command to check for system crashes. The...,"log show --predicate 'subsystem == ""com.apple.ReportCrash""' --last...",✔️ [1]
3,Can you explain the contents of the 'AI_Research_Projects' folder?,find ~/Documents/AI_Research_Projects -type f -exec cat {} ; | more,"To explain the contents of the 'AI_Research_Projects' folder, we c...",tree -L 1 AI_Research_Projects,✔️ [1]
4,What's inside the 'Reinforcement_Learning_Projects' folder?,find ~/Documents/Reinforcement_Learning_Projects -type f -exec cat...,"To see the contents of a directory in macOS, we can use the `ls` c...",ls -l Reinforcement_Learning_Projects,
5,Search through the 'Deep_Learning' folder and summarize its content,find ~/Documents/Deep_Learning -type f -exec cat {} ; | more,"To summarize the content of the 'Deep_Learning' folder, we can use...",brew install tree && tree -L 1 Deep_Learning,✔️ [1]
6,Search for 'ensemble learning' in my Documents,find ~/Documents -type f -exec grep -i -E 'ensemble\s*learning' {} ;,The `mdfind` command is used to search for files on macOS. The `kM...,"mdfind -onlyin ~/Documents 'kMDItemDisplayName == ""ensemble learni...",
7,Check the 'Research_Projects' folder for code using 'KNN',find ~/Documents/Research_Projects -type f -exec grep -i -E 'KNN|k...,The prompt asks to search for code using 'KNN' within the 'Researc...,"grep -rn ""KNN"" Research_Projects",✔️ [1]
8,Could you explain the contents of 'ML_Research' folder?,find ~/Documents/ML_Research -type f -exec cat {} ; | more,"To explain the contents of the 'ML_Research' folder, we can use th...",tree -L 1 ML_Research,
9,Look for any project files mentioning 'support vector machine' in ...,find ~/Documents -type f -exec grep -i -E 'support\s*vector\s*mach...,"We can use `mdfind` to search for files containing the phrase ""sup...","mdfind -onlyin ~/Documents ""support vector machine""",✔️ [1]
10,Play 'Watermelon Sugar' on YouTube using Firefox,if command -v firefox >/dev/null 2>&1; then firefox 'https://www.y...,This command opens Firefox and navigates to the YouTube search URL...,"open -a ""Firefox"" ""https://www.youtube.com/results?search_query=Wa...",✔️ [1]
11,Look for code that uses OpenCV in the 'Computer_Vision' folder,find ~/Documents/Computer_Vision -type f -exec grep -i -E 'opencv|...,"The command `grep -r ""cv2"" Computer_Vision` recursively searches f...","grep -r ""cv2"" Computer_Vision",✔️ [1]
12,What's inside the 'Text_Analysis_Projects' folder?,find ~/Documents/Text_Analysis_Projects -type f -exec cat {} ; | more,"To see the contents of a directory in macOS, we can use the `ls` c...",ls -la Text_Analysis_Projects,
13,Search for 'AI applications in healthcare' on Google using Safari,open -a Safari 'https://www.google.com/search?q=AI+applications+in...,We can use the `open` command with the `-a` flag to specify Safari...,"open -a Safari ""https://www.google.com/search?q=AI+applications+in...",✔️ [1]
14,Setup Python Django project with PostgreSQL,python3 -m venv venv && source venv/bin/activate && pip install dj...,1. **Create a virtual environment:** This isolates the project's d...,```bash python3 -m venv .venv source .venv/bin/activate pip instal...,✔️ [1]
15,Play 'Bad Guy' on YouTube using Firefox,if command -v firefox >/dev/null 2>&1; then firefox 'https://www.y...,This command opens Firefox and navigates to the YouTube URL for th...,"open -a ""Firefox"" ""https://www.youtube.com/results?search_query=Ba...",✔️ [1]
16,Look inside the 'ML_Research' folder for code using PyTorch,find ~/Documents/ML_Research -type f -exec grep -i -E 'torch|pytor...,"We can use `grep` to search for files containing the string ""torch...","grep -rn ""torch"" ML_Research",✔️ [1]
17,Find any research project in my Documents folder that talks about ...,find ~/Documents -type f -exec grep -i -E 'unsupervised\s*learning...,"We can use `mdfind` to search for files containing the phrase ""uns...","mdfind -onlyin ~/Documents ""unsupervised learning""",✔️ [1]
18,Find all large files (>100MB) in Documents,find ~/Documents -type f -size +100M,"To find all files larger than 100MB in the Documents directory, we...",find ~/Documents -type f -size +100M,✔️ [1]
19,Search for any code in 'Computer_Vision' related to 'object detect...,find ~/Documents/Computer_Vision -type f -exec grep -i -E 'object\...,The `grep` command can be used to search for text within files. Th...,"grep -ri --include=""*.py"" ""object detection"" Computer_Vision",✔️ [1]
20,Play 'Levitating' on Spotify,if command -v spotify >/dev/null 2>&1; then spotify play 'Levitati...,"This command opens the Spotify app and plays the song ""Levitating"".","open -a Spotify ""spotify:track:463CkQjx2Zk1yXoBuierM9""",✔️ [1]
21,Look for any projects in Documents related to 'feature selection',find ~/Documents -type f -exec grep -i -E 'feature\s*selection' {} ;,The prompt asks to find projects related to 'feature selection' wi...,"mdfind -onlyin ~/Documents ""feature selection""",✔️ [1]

Evaluation Results - Exact Match Accuracy: 81.82

In [118]:

from dspy.teleprompt import BootstrapFewShot, MIPROv2


from dspy.teleprompt import BootstrapFewShotWithRandomSearch
teleprompter = BootstrapFewShotWithRandomSearch( metric=metric,
    max_labeled_demos=100,  # Reduced from 16 to 8 for speed
    max_bootstrapped_demos=4,  # Reduced from 6
    num_candidate_programs=4,  # Reduced from 6
    num_threads=8)  # Parallel processing)
compiled_pred = teleprompter.compile(generator, trainset=train_examples)

Going to sample between 1 and 4 traces per predictor.
Will attempt to bootstrap 4 candidate sets.
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO
Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES


Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
NO


Validation Reasoning:
NO
Validation Reasoning:
NO

Validation Reasoning:
NO


  0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Validation Reasoning:
NO

Average Metric: 2.00 / 4 (50.0%):   2%|▏         | 3/192 [00:00<00:01, 133.95it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Average Metric: 3.00 / 5 (60.0%):   2%|▏         | 4/192 [00:00<00:01, 138.84it/s]Validation Reasoning:
YES


Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES
Average Metric: 4.00 / 6 (66.7%):   3%|▎         | 5/192 [00:00<00:01, 111.28it/s]
Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Average Metric: 5.00 / 7 (71.4%):   3%|▎         | 6/192 [00:00<00:01, 110.92it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Average Metric: 6.00 / 9 (66.7%):   4%|▍         | 8/192 [00:00<00:01, 117.19it/s]Validation Reasoning:
YES
Validation Reasoning:
NO


Average Metric: 6.00 / 10 (60.0%):   5%|▍         | 9/192 [00:00<00:01, 120.64it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 7.00 / 11 (63.6%):   5%|▌         | 10/192 [00:00<00:01, 119.95it/s]Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 8.00 / 12 (66.7%):   6%|▌         | 11/192 [00:00<00:01, 112.70it/s]Validation Reasoning:
NO
Average Metric: 8.00 / 13 (61.5%):   6%|▋         | 12/192 [00:00<00:01, 120.62it/s]
Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 8.00 / 13 (61.5%):   7%|▋         | 13/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO

Average Metric: 8.00 / 14 (57.1%):   7%|▋         | 13/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO

Average Metric: 8.00 / 15 (53.3%):   7%|▋         | 14/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
YES
Validation Reasoning:
NO


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 8.00 / 16 (50.0%):   8%|▊         | 15/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Average Metric: 8.00 / 18 (44.4%):   9%|▉         | 17/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO
Validation Reasoning:
YES


Average Metric: 8.00 / 19 (42.1%):   9%|▉         | 18/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES


Average Metric: 8.00 / 20 (40.0%):  10%|▉         | 19/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO

Average Metric: 9.00 / 22 (40.9%):  11%|█         | 21/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO

Validation Reasoning:
NO

Average Metric: 10.00 / 23 (43.5%):  11%|█▏        | 22/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
NO


Validation Reasoning:
YES

Average Metric: 11.00 / 24 (45.8%):  12%|█▏        | 23/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 12.00 / 25 (48.0%):  12%|█▎        | 24/192 [00:00<00:01, 107.40it/s]Validation Reasoning:
NO

Average Metric: 12.00 / 25 (48.0%):  13%|█▎        | 25/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Average Metric: 13.00 / 26 (50.0%):  13%|█▎        | 25/192 [00:00<00:01, 111.49it/s]
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO
Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 14.00 / 27 (51.9%):  14%|█▎        | 26/192 [00:00<00:01, 111.49it/s]
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO
Average Metric: 15.00 / 28 (53.6%):  14%|█▍        | 27/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
NO


Validation Reasoning:
NO
Validation Reasoning:
NO

Validation Reasoning:
YES


Validation Reasoning:
YES
Average Metric: 15.00 / 29 (51.7%):  15%|█▍        | 28/192 [00:00<00:01, 111.49it/s]
Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 17.00 / 31 (54.8%):  16%|█▌        | 30/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Average Metric: 18.00 / 32 (56.2%):  16%|█▌        | 31/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Average Metric: 18.00 / 33 (54.5%):  17%|█▋        | 32/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
NO
Average Metric: 18.00 / 34 (52.9%):  17%|█▋        | 33/192 [00:00<00:01, 111.49it/s]
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
NO

Average Metric: 18.00 / 36 (50.0%):  18%|█▊        | 35/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Average Metric: 19.00 / 37 (51.4%):  19%|█▉        | 36/192 [00:00<00:01, 111.49it/s]Validation Reasoning:
NO

Validation Reasoning:
NO
Validation Reasoning:
YES

Validation Reasoning:
NO


Validation Reasoning:
YES

Average Metric: 19.00 / 37 (51.4%):  19%|█▉        | 37/192 [00:00<00:01, 84.96it/s] Validation Reasoning:
YES

Average Metric: 20.00 / 38 (52.6%):  19%|█▉        | 37/192 [00:00<00:01, 84.96it/s]Validation Reasoning:
YES

Average Metric: 20.00 / 39 (51.3%):  20%|█▉        | 38/192 [00:00<00:01, 84.96it/s]Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 21.00 / 40 (52.5%):  20%|██        | 39/192 [00:00<00:01, 84.96it/s]Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
NO

Average Metric: 21.00 / 41 (51.2%):  21%|██        | 40/192 [00:00<00:01, 84.96it/s]Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO
Validation Reasoning:
NO

Average Metric: 21.00 / 42 (50.0%):  21%|██▏       | 41/192 [00:00<00:01, 84.96it/s]
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Average Metric: 110.00 / 192 (57.3%): 100%|██████████| 192/192 [00:01<00:00, 176.68it/s]

2025/05/01 02:10:12 INFO dspy.evaluate.evaluate: Average Metric: 110 / 192 (57.3%)

New best score: 57.29 for seed -3
Scores so far: [57.29]
Best score so far: 57.29
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

  0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
YES


Average Metric: 1.00 / 1 (100.0%):   0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 1.00 / 1 (100.0%):   1%|          | 1/192 [00:00<01:28,  2.17it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 1/192 [00:01<01:28,  2.17it/s]Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Average Metric: 2.00 / 2 (100.0%):   1%|          | 2/192 [00:01<02:57,  1.07it/s]Validation Reasoning:
YES

Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   1%|          | 2/192 [00:01<02:57,  1.07it/s]Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   2%|▏         | 3/192 [00:02<03:13,  1.02s/it]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES
Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 3/192 [00:03<03:13,  1.02s/it]

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 4/192 [00:04<03:20,  1.07s/it]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 5.00 / 5 (100.0%):   2%|▏         | 4/192 [00:05<03:20,  1.07s/it]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 5.00 / 5 (100.0%):   3%|▎         | 5/192 [00:05<03:28,  1.11s/it]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 181.00 / 192 (94.3%): 100%|██████████| 192/192 [00:05<00:00, 32.99it/s]

2025/05/01 02:10:20 INFO dspy.evaluate.evaluate: Average Metric: 181 / 192 (94.3%)

New best score: 94.27 for seed -2
Scores so far: [57.29, 94.27]
Best score so far: 94.27

  0%|          | 0/192 [00:00<?, ?it/s]

Validation Reasoning:
YES

Validation Reasoning:
YES

  1%|          | 2/192 [00:00<00:13, 14.35it/s]

Validation Reasoning:
YES

  2%|▏         | 4/192 [00:00<00:11, 15.99it/s]

Validation Reasoning:
YES

Bootstrapped 4 full traces after 4 examples for up to 1 rounds, amounting to 4 attempts.
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 1/192 [00:00<00:05, 36.81it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 2/192 [00:00<00:14, 13.39it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Average Metric: 3.00 / 3 (100.0%):   1%|          | 2/192 [00:00<00:14, 13.39it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 3/192 [00:01<00:14, 13.39it/s]
Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
NO

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES


Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 4/192 [00:02<01:49,  1.71it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Validation Reasoning:
YES

Validation Reasoning:
YES


Validation Reasoning:
YES

Average Metric: 5.00 / 5 (100.0%):   2%|▏         | 4/192 [00:02<01:49,  1.71it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES
Average Metric: 5.00 / 5 (100.0%):   3%|▎         | 5/192 [00:03<02:23,  1.31it/s]
Average Metric: 119.00 / 122 (97.5%):  63%|██████▎   | 121/192 [00:03<00:00, 107.73it/s]Validation Reasoning:
YES

Average Metric: 120.00 / 123 (97.6%):  64%|██████▍   | 123/192 [00:07<00:04, 14.81it/s] Validation Reasoning:
YES

Average Metric: 121.00 / 124 (97.6%):  64%|██████▍   | 123/192 [00:08<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 122.00 / 125 (97.6%):  65%|██████▍   | 124/192 [00:08<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 123.00 / 126 (97.6%):  65%|██████▌   | 125/192 [00:08<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 124.00 / 127 (97.6%):  66%|██████▌   | 126/192 [00:09<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 125.00 / 128 (97.7%):  66%|██████▌   | 127/192 [00:09<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 126.00 / 129 (97.7%):  67%|██████▋   | 128/192 [00:09<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 127.00 / 130 (97.7%):  67%|██████▋   | 129/192 [00:10<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 128.00 / 131 (97.7%):  68%|██████▊   | 130/192 [00:11<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 129.00 / 132 (97.7%):  68%|██████▊   | 131/192 [00:11<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 130.00 / 133 (97.7%):  69%|██████▉   | 132/192 [00:11<00:04, 14.81it/s]Validation Reasoning:
YES

Average Metric: 131.00 / 134 (97.8%):  69%|██████▉   | 133/192 [00:11<00:03, 14.81it/s]Validation Reasoning:
YES

Average Metric: 132.00 / 135 (97.8%):  70%|███████   | 135/192 [00:12<00:08,  6.92it/s]Validation Reasoning:
YES

Average Metric: 133.00 / 136 (97.8%):  70%|███████   | 135/192 [00:12<00:08,  6.92it/s]Validation Reasoning:
YES

Average Metric: 134.00 / 137 (97.8%):  71%|███████   | 136/192 [00:13<00:08,  6.92it/s]Validation Reasoning:
YES

Average Metric: 135.00 / 138 (97.8%):  71%|███████▏  | 137/192 [00:14<00:07,  6.92it/s]Validation Reasoning:
NO

Average Metric: 135.00 / 139 (97.1%):  72%|███████▏  | 138/192 [00:15<00:07,  6.92it/s]Validation Reasoning:
YES

Average Metric: 136.00 / 140 (97.1%):  72%|███████▏  | 139/192 [00:15<00:07,  6.92it/s]Validation Reasoning:
YES

Average Metric: 137.00 / 141 (97.2%):  73%|███████▎  | 140/192 [00:15<00:07,  6.92it/s]Validation Reasoning:
YES

Average Metric: 138.00 / 142 (97.2%):  73%|███████▎  | 141/192 [00:16<00:07,  6.92it/s]Validation Reasoning:
YES

Average Metric: 139.00 / 143 (97.2%):  74%|███████▍  | 142/192 [00:16<00:07,  6.92it/s]Validation Reasoning:
YES

Average Metric: 140.00 / 144 (97.2%):  75%|███████▌  | 144/192 [00:18<00:11,  4.34it/s]Validation Reasoning:
YES

Average Metric: 141.00 / 145 (97.2%):  75%|███████▌  | 144/192 [00:18<00:11,  4.34it/s]Validation Reasoning:
YES

Average Metric: 142.00 / 146 (97.3%):  76%|███████▌  | 145/192 [00:19<00:10,  4.34it/s]Validation Reasoning:
YES

Average Metric: 143.00 / 147 (97.3%):  76%|███████▌  | 146/192 [00:19<00:10,  4.34it/s]Validation Reasoning:
YES

Average Metric: 144.00 / 148 (97.3%):  77%|███████▋  | 147/192 [00:19<00:10,  4.34it/s]Validation Reasoning:
YES

Average Metric: 145.00 / 149 (97.3%):  77%|███████▋  | 148/192 [00:20<00:10,  4.34it/s]Validation Reasoning:
YES

Average Metric: 146.00 / 150 (97.3%):  78%|███████▊  | 150/192 [00:20<00:11,  3.75it/s]Validation Reasoning:
YES

Average Metric: 147.00 / 151 (97.4%):  78%|███████▊  | 150/192 [00:22<00:11,  3.75it/s]Validation Reasoning:
NO

Average Metric: 147.00 / 152 (96.7%):  79%|███████▊  | 151/192 [00:22<00:10,  3.75it/s]Validation Reasoning:
YES

Average Metric: 148.00 / 153 (96.7%):  79%|███████▉  | 152/192 [00:22<00:10,  3.75it/s]Validation Reasoning:
YES

Average Metric: 149.00 / 154 (96.8%):  80%|███████▉  | 153/192 [00:23<00:10,  3.75it/s]Validation Reasoning:
YES

Average Metric: 150.00 / 155 (96.8%):  81%|████████  | 155/192 [00:23<00:11,  3.33it/s]Validation Reasoning:
YES

Average Metric: 151.00 / 156 (96.8%):  81%|████████  | 155/192 [00:23<00:11,  3.33it/s]Validation Reasoning:
YES

Average Metric: 152.00 / 157 (96.8%):  81%|████████▏ | 156/192 [00:24<00:10,  3.33it/s]Validation Reasoning:
YES

Average Metric: 153.00 / 158 (96.8%):  82%|████████▏ | 157/192 [00:25<00:10,  3.33it/s]Validation Reasoning:
YES

Average Metric: 154.00 / 159 (96.9%):  82%|████████▏ | 158/192 [00:25<00:12,  2.70it/s]Validation Reasoning:
YES

Average Metric: 155.00 / 160 (96.9%):  83%|████████▎ | 159/192 [00:26<00:12,  2.70it/s]Validation Reasoning:
YES

Average Metric: 156.00 / 161 (96.9%):  84%|████████▍ | 161/192 [00:26<00:10,  2.83it/s]Validation Reasoning:
NO

Average Metric: 156.00 / 162 (96.3%):  84%|████████▍ | 161/192 [00:27<00:10,  2.83it/s]Validation Reasoning:
YES

Average Metric: 157.00 / 163 (96.3%):  85%|████████▍ | 163/192 [00:27<00:10,  2.83it/s]Validation Reasoning:
YES

Average Metric: 158.00 / 164 (96.3%):  85%|████████▍ | 163/192 [00:28<00:10,  2.83it/s]Validation Reasoning:
YES

Average Metric: 159.00 / 165 (96.4%):  86%|████████▌ | 165/192 [00:28<00:11,  2.42it/s]Validation Reasoning:
YES

Average Metric: 160.00 / 166 (96.4%):  86%|████████▋ | 166/192 [00:29<00:10,  2.39it/s]Validation Reasoning:
YES

Average Metric: 161.00 / 167 (96.4%):  87%|████████▋ | 167/192 [00:29<00:10,  2.46it/s]Validation Reasoning:
YES

Average Metric: 162.00 / 168 (96.4%):  87%|████████▋ | 167/192 [00:29<00:10,  2.46it/s]Validation Reasoning:
YES

Average Metric: 163.00 / 169 (96.4%):  88%|████████▊ | 169/192 [00:30<00:08,  2.82it/s]Validation Reasoning:
YES

Average Metric: 164.00 / 170 (96.5%):  89%|████████▊ | 170/192 [00:30<00:08,  2.59it/s]Validation Reasoning:
YES

Average Metric: 165.00 / 171 (96.5%):  89%|████████▉ | 171/192 [00:32<00:13,  1.56it/s]Validation Reasoning:
YES

Average Metric: 166.00 / 172 (96.5%):  90%|████████▉ | 172/192 [00:32<00:12,  1.63it/s]Validation Reasoning:
YES

Average Metric: 167.00 / 173 (96.5%):  90%|█████████ | 173/192 [00:33<00:10,  1.87it/s]Validation Reasoning:
YES

Average Metric: 168.00 / 174 (96.6%):  91%|█████████ | 174/192 [00:33<00:08,  2.07it/s]Validation Reasoning:
YES

Average Metric: 169.00 / 175 (96.6%):  91%|█████████ | 174/192 [00:33<00:08,  2.07it/s]Validation Reasoning:
YES

Average Metric: 170.00 / 176 (96.6%):  92%|█████████▏| 176/192 [00:33<00:05,  2.73it/s]Validation Reasoning:
YES

Average Metric: 171.00 / 177 (96.6%):  92%|█████████▏| 177/192 [00:34<00:05,  2.98it/s]Validation Reasoning:
YES

Average Metric: 172.00 / 178 (96.6%):  93%|█████████▎| 178/192 [00:36<00:10,  1.29it/s]Validation Reasoning:
NO

Average Metric: 172.00 / 179 (96.1%):  93%|█████████▎| 179/192 [00:36<00:08,  1.45it/s]Validation Reasoning:
YES

Average Metric: 173.00 / 180 (96.1%):  94%|█████████▍| 180/192 [00:37<00:06,  1.73it/s]Validation Reasoning:
YES

Average Metric: 174.00 / 181 (96.1%):  94%|█████████▍| 181/192 [00:37<00:06,  1.80it/s]Validation Reasoning:
NO

Average Metric: 174.00 / 182 (95.6%):  94%|█████████▍| 181/192 [00:37<00:06,  1.80it/s]Validation Reasoning:
YES

Average Metric: 175.00 / 183 (95.6%):  95%|█████████▌| 183/192 [00:37<00:03,  2.46it/s]Validation Reasoning:
YES

Average Metric: 176.00 / 184 (95.7%):  96%|█████████▌| 184/192 [00:39<00:05,  1.47it/s]Validation Reasoning:
YES

Average Metric: 177.00 / 185 (95.7%):  96%|█████████▋| 185/192 [00:39<00:04,  1.74it/s]Validation Reasoning:
YES

Average Metric: 178.00 / 186 (95.7%):  97%|█████████▋| 186/192 [00:39<00:02,  2.12it/s]Validation Reasoning:
YES

Average Metric: 179.00 / 187 (95.7%):  97%|█████████▋| 187/192 [00:40<00:02,  2.47it/s]Validation Reasoning:
YES

Average Metric: 180.00 / 188 (95.7%):  98%|█████████▊| 188/192 [00:40<00:01,  3.05it/s]Validation Reasoning:
YES

Average Metric: 181.00 / 189 (95.8%):  98%|█████████▊| 189/192 [00:40<00:01,  2.75it/s]Validation Reasoning:
YES

Average Metric: 182.00 / 190 (95.8%):  99%|█████████▉| 190/192 [00:43<00:01,  1.01it/s]Validation Reasoning:
YES

Average Metric: 183.00 / 191 (95.8%):  99%|█████████▉| 191/192 [00:44<00:00,  1.07it/s]Validation Reasoning:
YES

Average Metric: 184.00 / 192 (95.8%): 100%|██████████| 192/192 [00:45<00:00,  4.18it/s]

2025/05/01 02:11:09 INFO dspy.evaluate.evaluate: Average Metric: 184 / 192 (95.8%)

New best score: 95.83 for seed -1
Scores so far: [57.29, 94.27, 95.83]
Best score so far: 95.83

  1%|          | 1/192 [00:04<12:57,  4.07s/it]

Validation Reasoning:
YES

  1%|          | 2/192 [00:08<14:02,  4.43s/it]

Validation Reasoning:
NO

  2%|▏         | 3/192 [00:11<12:00,  3.81s/it]

Validation Reasoning:
YES

  2%|▏         | 4/192 [00:16<13:07,  4.19s/it]

Validation Reasoning:
NO

  3%|▎         | 5/192 [00:19<11:59,  3.85s/it]

Validation Reasoning:
YES

  3%|▎         | 6/192 [00:22<11:40,  3.76s/it]

Validation Reasoning:
YES

Bootstrapped 4 full traces after 6 examples for up to 1 rounds, amounting to 6 attempts.

  0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Average Metric: 1.00 / 1 (100.0%):   1%|          | 1/192 [00:03<10:26,  3.28s/it]Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 1/192 [00:03<10:26,  3.28s/it]Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   2%|▏         | 3/192 [00:03<02:57,  1.06it/s]Validation Reasoning:
YES

Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 4/192 [00:03<02:03,  1.52it/s]Validation Reasoning:
YES

Average Metric: 5.00 / 5 (100.0%):   3%|▎         | 5/192 [00:03<01:30,  2.06it/s]Validation Reasoning:
YES

Average Metric: 6.00 / 6 (100.0%):   3%|▎         | 5/192 [00:03<01:30,  2.06it/s]Validation Reasoning:
YES

Average Metric: 7.00 / 7 (100.0%):   4%|▎         | 7/192 [00:06<03:06,  1.01s/it]Validation Reasoning:
YES

Average Metric: 8.00 / 8 (100.0%):   4%|▎         | 7/192 [00:06<03:06,  1.01s/it]Validation Reasoning:
YES

Average Metric: 9.00 / 9 (100.0%):   5%|▍         | 9/192 [00:07<01:56,  1.56it/s]Validation Reasoning:
YES

Average Metric: 10.00 / 10 (100.0%):   5%|▌         | 10/192 [00:07<01:34,  1.93it/s]Validation Reasoning:
YES

Average Metric: 11.00 / 11 (100.0%):   6%|▌         | 11/192 [00:08<01:50,  1.63it/s]Validation Reasoning:
YES

Average Metric: 12.00 / 12 (100.0%):   6%|▋         | 12/192 [00:10<02:53,  1.04it/s]Validation Reasoning:
YES

Average Metric: 13.00 / 13 (100.0%):   7%|▋         | 13/192 [00:10<02:12,  1.35it/s]Validation Reasoning:
YES

Average Metric: 14.00 / 14 (100.0%):   7%|▋         | 14/192 [00:11<02:28,  1.20it/s]Validation Reasoning:
YES

Average Metric: 15.00 / 15 (100.0%):   7%|▋         | 14/192 [00:11<02:28,  1.20it/s]Validation Reasoning:
YES

Average Metric: 16.00 / 16 (100.0%):   8%|▊         | 16/192 [00:11<01:26,  2.04it/s]Validation Reasoning:
YES

Average Metric: 17.00 / 17 (100.0%):   9%|▉         | 17/192 [00:11<01:09,  2.51it/s]Validation Reasoning:
YES

Average Metric: 18.00 / 18 (100.0%):   9%|▉         | 18/192 [00:11<01:03,  2.74it/s]Validation Reasoning:
NO

Average Metric: 18.00 / 19 (94.7%):  10%|▉         | 19/192 [00:12<01:02,  2.76it/s] Validation Reasoning:
YES

Average Metric: 19.00 / 20 (95.0%):  10%|█         | 20/192 [00:13<01:35,  1.80it/s]Validation Reasoning:
YES

Average Metric: 20.00 / 21 (95.2%):  11%|█         | 21/192 [00:14<02:07,  1.34it/s]Validation Reasoning:
YES

Average Metric: 21.00 / 22 (95.5%):  11%|█▏        | 22/192 [00:14<01:36,  1.77it/s]Validation Reasoning:
YES

Average Metric: 22.00 / 23 (95.7%):  12%|█▏        | 23/192 [00:14<01:13,  2.29it/s]Validation Reasoning:
YES

Average Metric: 23.00 / 24 (95.8%):  12%|█▎        | 24/192 [00:14<01:04,  2.61it/s]Validation Reasoning:
YES

Average Metric: 24.00 / 25 (96.0%):  13%|█▎        | 25/192 [00:15<01:06,  2.51it/s]Validation Reasoning:
YES

Average Metric: 25.00 / 26 (96.2%):  14%|█▎        | 26/192 [00:17<02:07,  1.30it/s]Validation Reasoning:
YES

Average Metric: 26.00 / 27 (96.3%):  14%|█▍        | 27/192 [00:18<02:35,  1.06it/s]Validation Reasoning:
YES

Average Metric: 27.00 / 28 (96.4%):  15%|█▍        | 28/192 [00:18<01:55,  1.42it/s]Validation Reasoning:
YES

Average Metric: 28.00 / 29 (96.6%):  15%|█▌        | 29/192 [00:21<03:21,  1.24s/it]Validation Reasoning:
YES

Average Metric: 29.00 / 30 (96.7%):  15%|█▌        | 29/192 [00:21<03:21,  1.24s/it]Validation Reasoning:
YES

Average Metric: 30.00 / 31 (96.8%):  16%|█▌        | 30/192 [00:21<03:02,  1.13s/it]Validation Reasoning:
YES

Average Metric: 31.00 / 32 (96.9%):  17%|█▋        | 32/192 [00:22<01:45,  1.51it/s]Validation Reasoning:
YES

Average Metric: 32.00 / 33 (97.0%):  17%|█▋        | 33/192 [00:22<01:28,  1.79it/s]Validation Reasoning:
NO

Average Metric: 32.00 / 34 (94.1%):  18%|█▊        | 34/192 [00:22<01:13,  2.15it/s]Validation Reasoning:
YES

Average Metric: 33.00 / 35 (94.3%):  18%|█▊        | 35/192 [00:24<02:11,  1.20it/s]Validation Reasoning:
YES

Average Metric: 34.00 / 36 (94.4%):  19%|█▉        | 36/192 [00:25<02:24,  1.08it/s]Validation Reasoning:
YES

Average Metric: 35.00 / 37 (94.6%):  19%|█▉        | 37/192 [00:26<02:18,  1.12it/s]Validation Reasoning:
YES

Average Metric: 36.00 / 38 (94.7%):  20%|█▉        | 38/192 [00:27<02:08,  1.20it/s]Validation Reasoning:
YES

Average Metric: 37.00 / 39 (94.9%):  20%|██        | 39/192 [00:27<02:06,  1.21it/s]Validation Reasoning:
YES

Average Metric: 38.00 / 40 (95.0%):  21%|██        | 40/192 [00:29<02:22,  1.07it/s]Validation Reasoning:
YES

Average Metric: 39.00 / 41 (95.1%):  21%|██▏       | 41/192 [00:29<01:50,  1.36it/s]Validation Reasoning:
YES

Average Metric: 40.00 / 42 (95.2%):  22%|██▏       | 42/192 [00:30<02:23,  1.04it/s]Validation Reasoning:
YES

Average Metric: 41.00 / 43 (95.3%):  22%|██▏       | 43/192 [00:31<01:52,  1.33it/s]Validation Reasoning:
NO

Average Metric: 41.00 / 44 (93.2%):  22%|██▏       | 43/192 [00:31<01:52,  1.33it/s]Validation Reasoning:
YES

Average Metric: 42.00 / 45 (93.3%):  23%|██▎       | 45/192 [00:31<01:24,  1.74it/s]Validation Reasoning:
YES

Average Metric: 43.00 / 46 (93.5%):  24%|██▍       | 46/192 [00:32<01:34,  1.54it/s]Validation Reasoning:
YES

Average Metric: 44.00 / 47 (93.6%):  24%|██▍       | 46/192 [00:32<01:34,  1.54it/s]Validation Reasoning:
YES

Average Metric: 45.00 / 48 (93.8%):  25%|██▌       | 48/192 [00:33<01:20,  1.80it/s]Validation Reasoning:
YES

Average Metric: 46.00 / 49 (93.9%):  26%|██▌       | 49/192 [00:34<01:43,  1.38it/s]Validation Reasoning:
YES

Average Metric: 47.00 / 50 (94.0%):  26%|██▌       | 50/192 [00:36<02:18,  1.02it/s]Validation Reasoning:
YES

Average Metric: 48.00 / 51 (94.1%):  26%|██▌       | 50/192 [00:36<02:18,  1.02it/s]Validation Reasoning:
YES

Average Metric: 49.00 / 52 (94.2%):  27%|██▋       | 52/192 [00:38<02:04,  1.13it/s]Validation Reasoning:
YES

Average Metric: 50.00 / 53 (94.3%):  28%|██▊       | 53/192 [00:38<01:39,  1.40it/s]Validation Reasoning:
YES

Average Metric: 51.00 / 54 (94.4%):  28%|██▊       | 54/192 [00:39<01:41,  1.36it/s]Validation Reasoning:
YES

Average Metric: 52.00 / 55 (94.5%):  29%|██▊       | 55/192 [00:40<02:03,  1.11it/s]Validation Reasoning:
YES

Average Metric: 53.00 / 56 (94.6%):  29%|██▊       | 55/192 [00:40<02:03,  1.11it/s]Validation Reasoning:
NO

Average Metric: 53.00 / 57 (93.0%):  30%|██▉       | 57/192 [00:40<01:14,  1.82it/s]Validation Reasoning:
YES

Average Metric: 54.00 / 58 (93.1%):  30%|███       | 58/192 [00:41<01:35,  1.40it/s]Validation Reasoning:
YES

Average Metric: 55.00 / 59 (93.2%):  31%|███       | 59/192 [00:42<01:31,  1.46it/s]Validation Reasoning:
YES

Average Metric: 56.00 / 60 (93.3%):  31%|███▏      | 60/192 [00:43<01:33,  1.41it/s]Validation Reasoning:
YES

Average Metric: 57.00 / 61 (93.4%):  32%|███▏      | 61/192 [00:43<01:18,  1.67it/s]Validation Reasoning:
YES

Average Metric: 58.00 / 62 (93.5%):  32%|███▏      | 62/192 [00:43<01:04,  2.02it/s]Validation Reasoning:
YES

Average Metric: 59.00 / 63 (93.7%):  33%|███▎      | 63/192 [00:46<02:20,  1.09s/it]Validation Reasoning:
YES

Average Metric: 60.00 / 64 (93.8%):  33%|███▎      | 63/192 [00:46<02:20,  1.09s/it]Validation Reasoning:
YES

Average Metric: 61.00 / 65 (93.8%):  33%|███▎      | 64/192 [00:46<01:52,  1.14it/s]Validation Reasoning:
NO

Average Metric: 61.00 / 66 (92.4%):  34%|███▍      | 66/192 [00:48<01:41,  1.24it/s]Validation Reasoning:
YES

Average Metric: 62.00 / 67 (92.5%):  35%|███▍      | 67/192 [00:49<01:43,  1.20it/s]Validation Reasoning:
NO

Average Metric: 62.00 / 68 (91.2%):  35%|███▌      | 68/192 [00:49<01:45,  1.18it/s]Validation Reasoning:
YES

Average Metric: 63.00 / 69 (91.3%):  36%|███▌      | 69/192 [00:50<01:30,  1.36it/s]Validation Reasoning:
YES

Average Metric: 64.00 / 70 (91.4%):  36%|███▋      | 70/192 [00:50<01:25,  1.43it/s]Validation Reasoning:
YES

Average Metric: 65.00 / 71 (91.5%):  37%|███▋      | 71/192 [00:51<01:14,  1.63it/s]Validation Reasoning:
YES

Average Metric: 66.00 / 72 (91.7%):  38%|███▊      | 72/192 [00:53<02:07,  1.07s/it]Validation Reasoning:
YES

Average Metric: 67.00 / 73 (91.8%):  38%|███▊      | 73/192 [00:53<01:34,  1.26it/s]Validation Reasoning:
YES

Average Metric: 68.00 / 74 (91.9%):  39%|███▊      | 74/192 [00:54<01:42,  1.15it/s]Validation Reasoning:
NO

Average Metric: 68.00 / 75 (90.7%):  39%|███▉      | 75/192 [00:55<01:36,  1.21it/s]Validation Reasoning:
YES

Average Metric: 69.00 / 76 (90.8%):  40%|███▉      | 76/192 [00:56<01:29,  1.29it/s]Validation Reasoning:
YES

Average Metric: 70.00 / 77 (90.9%):  40%|████      | 77/192 [00:56<01:26,  1.33it/s]Validation Reasoning:
YES

Average Metric: 71.00 / 78 (91.0%):  41%|████      | 78/192 [00:57<01:14,  1.54it/s]Validation Reasoning:
YES

Average Metric: 72.00 / 79 (91.1%):  41%|████      | 79/192 [00:57<01:06,  1.69it/s]Validation Reasoning:
YES

Average Metric: 73.00 / 80 (91.2%):  42%|████▏     | 80/192 [00:58<01:06,  1.68it/s]Validation Reasoning:
NO

Average Metric: 73.00 / 81 (90.1%):  42%|████▏     | 81/192 [00:58<00:52,  2.12it/s]Validation Reasoning:
YES

Average Metric: 74.00 / 82 (90.2%):  43%|████▎     | 82/192 [00:58<00:46,  2.38it/s]Validation Reasoning:
YES

Average Metric: 75.00 / 83 (90.4%):  43%|████▎     | 83/192 [00:59<01:09,  1.57it/s]Validation Reasoning:
YES

Average Metric: 76.00 / 84 (90.5%):  44%|████▍     | 84/192 [01:00<01:18,  1.38it/s]Validation Reasoning:
YES

Average Metric: 77.00 / 85 (90.6%):  44%|████▍     | 85/192 [01:01<01:28,  1.21it/s]Validation Reasoning:
YES

Average Metric: 78.00 / 86 (90.7%):  45%|████▍     | 86/192 [01:02<01:27,  1.22it/s]Validation Reasoning:
YES

Average Metric: 79.00 / 87 (90.8%):  45%|████▌     | 87/192 [01:02<01:07,  1.55it/s]Validation Reasoning:
YES

Average Metric: 80.00 / 88 (90.9%):  46%|████▌     | 88/192 [01:03<01:01,  1.70it/s]Validation Reasoning:
YES

Average Metric: 81.00 / 89 (91.0%):  46%|████▋     | 89/192 [01:04<01:09,  1.49it/s]Validation Reasoning:
YES

Average Metric: 82.00 / 90 (91.1%):  47%|████▋     | 90/192 [01:04<00:58,  1.76it/s]Validation Reasoning:
YES

Average Metric: 83.00 / 91 (91.2%):  47%|████▋     | 91/192 [01:04<00:46,  2.17it/s]Validation Reasoning:
YES

Average Metric: 84.00 / 92 (91.3%):  48%|████▊     | 92/192 [01:05<00:56,  1.76it/s]Validation Reasoning:
YES

Average Metric: 85.00 / 93 (91.4%):  48%|████▊     | 93/192 [01:05<00:42,  2.31it/s]Validation Reasoning:
YES

Average Metric: 86.00 / 94 (91.5%):  49%|████▉     | 94/192 [01:07<01:25,  1.15it/s]Validation Reasoning:
YES

Average Metric: 87.00 / 95 (91.6%):  49%|████▉     | 94/192 [01:07<01:25,  1.15it/s]Validation Reasoning:
YES

Average Metric: 88.00 / 96 (91.7%):  50%|█████     | 96/192 [01:07<00:52,  1.84it/s]Validation Reasoning:
YES

Average Metric: 89.00 / 97 (91.8%):  51%|█████     | 97/192 [01:08<00:42,  2.23it/s]Validation Reasoning:
YES

Average Metric: 90.00 / 98 (91.8%):  51%|█████     | 98/192 [01:08<00:38,  2.47it/s]Validation Reasoning:
YES

Average Metric: 91.00 / 99 (91.9%):  52%|█████▏    | 99/192 [01:08<00:34,  2.67it/s]Validation Reasoning:
YES

Average Metric: 92.00 / 100 (92.0%):  52%|█████▏    | 100/192 [01:08<00:31,  2.88it/s]Validation Reasoning:
YES

Average Metric: 93.00 / 101 (92.1%):  53%|█████▎    | 101/192 [01:10<01:15,  1.20it/s]Validation Reasoning:
YES

Average Metric: 94.00 / 102 (92.2%):  53%|█████▎    | 102/192 [01:11<00:57,  1.57it/s]Validation Reasoning:
YES

Average Metric: 95.00 / 103 (92.2%):  54%|█████▎    | 103/192 [01:11<00:48,  1.82it/s]Validation Reasoning:
YES

Average Metric: 96.00 / 104 (92.3%):  54%|█████▎    | 103/192 [01:11<00:48,  1.82it/s]Validation Reasoning:
YES

Average Metric: 97.00 / 105 (92.4%):  55%|█████▍    | 105/192 [01:11<00:35,  2.47it/s]Validation Reasoning:
YES

Average Metric: 98.00 / 106 (92.5%):  55%|█████▌    | 106/192 [01:12<00:42,  2.02it/s]Validation Reasoning:
YES

Average Metric: 99.00 / 107 (92.5%):  56%|█████▌    | 107/192 [01:13<00:45,  1.88it/s]Validation Reasoning:
YES

Average Metric: 100.00 / 108 (92.6%):  56%|█████▋    | 108/192 [01:14<00:56,  1.48it/s]Validation Reasoning:
YES

Average Metric: 101.00 / 109 (92.7%):  56%|█████▋    | 108/192 [01:14<00:56,  1.48it/s]Validation Reasoning:
YES

Average Metric: 102.00 / 110 (92.7%):  57%|█████▋    | 110/192 [01:15<00:47,  1.73it/s]Validation Reasoning:
YES

Average Metric: 103.00 / 111 (92.8%):  58%|█████▊    | 111/192 [01:15<00:38,  2.08it/s]Validation Reasoning:
YES

Average Metric: 104.00 / 112 (92.9%):  58%|█████▊    | 112/192 [01:15<00:31,  2.57it/s]Validation Reasoning:
YES

Average Metric: 105.00 / 113 (92.9%):  59%|█████▉    | 113/192 [01:16<00:38,  2.06it/s]Validation Reasoning:
NO

Average Metric: 105.00 / 114 (92.1%):  59%|█████▉    | 114/192 [01:16<00:34,  2.28it/s]Validation Reasoning:
YES

Average Metric: 106.00 / 115 (92.2%):  60%|█████▉    | 115/192 [01:18<01:14,  1.03it/s]Validation Reasoning:
YES

Average Metric: 107.00 / 116 (92.2%):  60%|██████    | 116/192 [01:19<00:56,  1.35it/s]Validation Reasoning:
YES

Average Metric: 108.00 / 117 (92.3%):  61%|██████    | 117/192 [01:19<00:43,  1.73it/s]Validation Reasoning:
NO

Average Metric: 108.00 / 118 (91.5%):  61%|██████▏   | 118/192 [01:20<01:06,  1.12it/s]Validation Reasoning:
YES

Average Metric: 109.00 / 119 (91.6%):  61%|██████▏   | 118/192 [01:21<01:06,  1.12it/s]Validation Reasoning:
YES

Average Metric: 110.00 / 120 (91.7%):  62%|██████▎   | 120/192 [01:21<00:38,  1.88it/s]Validation Reasoning:
YES

Average Metric: 111.00 / 121 (91.7%):  62%|██████▎   | 120/192 [01:21<00:38,  1.88it/s]Validation Reasoning:
YES

Average Metric: 112.00 / 122 (91.8%):  64%|██████▎   | 122/192 [01:22<00:37,  1.86it/s]Validation Reasoning:
YES

Average Metric: 113.00 / 123 (91.9%):  64%|██████▍   | 123/192 [01:22<00:33,  2.06it/s]Validation Reasoning:
YES

Average Metric: 114.00 / 124 (91.9%):  65%|██████▍   | 124/192 [01:23<00:37,  1.83it/s]Validation Reasoning:
YES

Average Metric: 115.00 / 125 (92.0%):  65%|██████▌   | 125/192 [01:23<00:37,  1.78it/s]Validation Reasoning:
YES

Average Metric: 116.00 / 126 (92.1%):  66%|██████▌   | 126/192 [01:24<00:36,  1.79it/s]Validation Reasoning:
YES

Average Metric: 117.00 / 127 (92.1%):  66%|██████▌   | 127/192 [01:25<00:35,  1.82it/s]Validation Reasoning:
YES

Average Metric: 118.00 / 128 (92.2%):  67%|██████▋   | 128/192 [01:26<00:44,  1.44it/s]Validation Reasoning:
YES

Average Metric: 119.00 / 129 (92.2%):  67%|██████▋   | 128/192 [01:26<00:44,  1.44it/s]Validation Reasoning:
YES

Average Metric: 120.00 / 130 (92.3%):  68%|██████▊   | 130/192 [01:26<00:27,  2.23it/s]Validation Reasoning:
YES

Average Metric: 121.00 / 131 (92.4%):  68%|██████▊   | 131/192 [01:28<00:45,  1.33it/s]Validation Reasoning:
YES

Average Metric: 122.00 / 132 (92.4%):  68%|██████▊   | 131/192 [01:28<00:45,  1.33it/s]Validation Reasoning:
NO

Average Metric: 122.00 / 133 (91.7%):  69%|██████▉   | 133/192 [01:28<00:31,  1.85it/s]Validation Reasoning:
YES

Average Metric: 123.00 / 134 (91.8%):  70%|██████▉   | 134/192 [01:29<00:41,  1.41it/s]Validation Reasoning:
YES

Average Metric: 124.00 / 135 (91.9%):  70%|███████   | 135/192 [01:30<00:38,  1.48it/s]Validation Reasoning:
NO

Average Metric: 124.00 / 136 (91.2%):  70%|███████   | 135/192 [01:30<00:38,  1.48it/s]Validation Reasoning:
YES

Average Metric: 125.00 / 137 (91.2%):  71%|███████▏  | 137/192 [01:31<00:29,  1.84it/s]Validation Reasoning:
YES

Average Metric: 126.00 / 138 (91.3%):  72%|███████▏  | 138/192 [01:31<00:24,  2.19it/s]Validation Reasoning:
YES

Average Metric: 127.00 / 139 (91.4%):  72%|███████▏  | 139/192 [01:31<00:22,  2.34it/s]Validation Reasoning:
YES

Average Metric: 128.00 / 140 (91.4%):  73%|███████▎  | 140/192 [01:31<00:21,  2.44it/s]Validation Reasoning:
YES

Average Metric: 129.00 / 141 (91.5%):  73%|███████▎  | 141/192 [01:33<00:33,  1.53it/s]Validation Reasoning:
YES

Average Metric: 130.00 / 142 (91.5%):  74%|███████▍  | 142/192 [01:33<00:26,  1.85it/s]Validation Reasoning:
YES

Average Metric: 131.00 / 143 (91.6%):  74%|███████▍  | 143/192 [01:33<00:23,  2.11it/s]Validation Reasoning:
YES

Average Metric: 132.00 / 144 (91.7%):  75%|███████▌  | 144/192 [01:34<00:21,  2.26it/s]Validation Reasoning:
NO

Average Metric: 132.00 / 145 (91.0%):  76%|███████▌  | 145/192 [01:34<00:22,  2.07it/s]Validation Reasoning:
NO

Average Metric: 132.00 / 146 (90.4%):  76%|███████▌  | 146/192 [01:35<00:24,  1.87it/s]Validation Reasoning:
NO

Average Metric: 132.00 / 147 (89.8%):  77%|███████▋  | 147/192 [01:36<00:25,  1.74it/s]Validation Reasoning:
YES

Average Metric: 133.00 / 148 (89.9%):  77%|███████▋  | 148/192 [01:37<00:32,  1.37it/s]Validation Reasoning:
YES

Average Metric: 134.00 / 149 (89.9%):  77%|███████▋  | 148/192 [01:37<00:32,  1.37it/s]Validation Reasoning:
YES

Average Metric: 135.00 / 150 (90.0%):  78%|███████▊  | 150/192 [01:37<00:20,  2.02it/s]Validation Reasoning:
YES

Average Metric: 136.00 / 151 (90.1%):  79%|███████▊  | 151/192 [01:37<00:17,  2.40it/s]Validation Reasoning:
YES

Average Metric: 137.00 / 152 (90.1%):  79%|███████▉  | 152/192 [01:38<00:16,  2.40it/s]Validation Reasoning:
YES

Average Metric: 138.00 / 153 (90.2%):  80%|███████▉  | 153/192 [01:38<00:16,  2.36it/s]Validation Reasoning:
YES

Average Metric: 139.00 / 154 (90.3%):  80%|████████  | 154/192 [01:40<00:35,  1.08it/s]Validation Reasoning:
YES

Average Metric: 140.00 / 155 (90.3%):  81%|████████  | 155/192 [01:41<00:29,  1.24it/s]Validation Reasoning:
NO

Average Metric: 140.00 / 156 (89.7%):  81%|████████▏ | 156/192 [01:41<00:24,  1.48it/s]Validation Reasoning:
YES

Average Metric: 141.00 / 157 (89.8%):  82%|████████▏ | 157/192 [01:41<00:19,  1.82it/s]Validation Reasoning:
YES

Average Metric: 142.00 / 158 (89.9%):  82%|████████▏ | 158/192 [01:42<00:14,  2.38it/s]Validation Reasoning:
YES

Average Metric: 143.00 / 159 (89.9%):  83%|████████▎ | 159/192 [01:44<00:32,  1.02it/s]Validation Reasoning:
YES

Average Metric: 144.00 / 160 (90.0%):  83%|████████▎ | 160/192 [01:44<00:25,  1.25it/s]Validation Reasoning:
YES

Average Metric: 145.00 / 161 (90.1%):  84%|████████▍ | 161/192 [01:44<00:19,  1.59it/s]Validation Reasoning:
YES

Average Metric: 146.00 / 162 (90.1%):  84%|████████▍ | 161/192 [01:45<00:19,  1.59it/s]Validation Reasoning:
YES

Average Metric: 147.00 / 163 (90.2%):  85%|████████▍ | 163/192 [01:45<00:11,  2.55it/s]Validation Reasoning:
YES

Average Metric: 148.00 / 164 (90.2%):  85%|████████▌ | 164/192 [01:46<00:13,  2.02it/s]Validation Reasoning:
YES

Average Metric: 149.00 / 165 (90.3%):  86%|████████▌ | 165/192 [01:48<00:25,  1.08it/s]Validation Reasoning:
YES

Average Metric: 150.00 / 166 (90.4%):  86%|████████▋ | 166/192 [01:48<00:18,  1.41it/s]Validation Reasoning:
YES

Average Metric: 151.00 / 167 (90.4%):  86%|████████▋ | 166/192 [01:48<00:18,  1.41it/s]Validation Reasoning:
YES

Average Metric: 152.00 / 168 (90.5%):  88%|████████▊ | 168/192 [01:48<00:12,  1.94it/s]Validation Reasoning:
YES

Average Metric: 153.00 / 169 (90.5%):  88%|████████▊ | 168/192 [01:48<00:12,  1.94it/s]Validation Reasoning:
YES

Average Metric: 154.00 / 170 (90.6%):  89%|████████▊ | 170/192 [01:49<00:09,  2.42it/s]Validation Reasoning:
NO

Average Metric: 154.00 / 171 (90.1%):  89%|████████▉ | 171/192 [01:50<00:10,  1.98it/s]Validation Reasoning:
NO

Average Metric: 154.00 / 172 (89.5%):  90%|████████▉ | 172/192 [01:50<00:09,  2.21it/s]Validation Reasoning:
YES

Average Metric: 155.00 / 173 (89.6%):  90%|█████████ | 173/192 [01:50<00:07,  2.43it/s]Validation Reasoning:
YES

Average Metric: 156.00 / 174 (89.7%):  91%|█████████ | 174/192 [01:52<00:11,  1.53it/s]Validation Reasoning:
YES

Average Metric: 157.00 / 175 (89.7%):  91%|█████████ | 174/192 [01:52<00:11,  1.53it/s]Validation Reasoning:
YES

Average Metric: 158.00 / 176 (89.8%):  92%|█████████▏| 176/192 [01:52<00:06,  2.48it/s]Validation Reasoning:
YES

Average Metric: 159.00 / 177 (89.8%):  92%|█████████▏| 177/192 [01:52<00:05,  2.54it/s]Validation Reasoning:
YES


2025/05/01 02:13:36 INFO dspy.evaluate.evaluate: Average Metric: 173 / 192 (90.1%)

Scores so far: [57.29, 94.27, 95.83, 90.1]
Best score so far: 95.83

  1%|          | 1/192 [00:02<07:24,  2.33s/it]

Validation Reasoning:
YES

  1%|          | 2/192 [00:04<07:36,  2.40s/it]

Validation Reasoning:
YES

Bootstrapped 2 full traces after 2 examples for up to 1 rounds, amounting to 2 attempts.
  0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Average Metric: 1.00 / 1 (100.0%):   1%|          | 1/192 [00:02<09:26,  2.96s/it]Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 1/192 [00:02<09:26,  2.96s/it]Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   2%|▏         | 3/192 [00:03<02:39,  1.19it/s]Validation Reasoning:
YES

Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 4/192 [00:03<01:52,  1.68it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 6.00 / 6 (100.0%):   3%|▎         | 5/192 [00:03<01:25,  2.20it/s]Validation Reasoning:
YES

Average Metric: 7.00 / 7 (100.0%):   4%|▎         | 7/192 [00:03<00:47,  3.86it/s]Validation Reasoning:
YES

Average Metric: 8.00 / 8 (100.0%):   4%|▎         | 7/192 [00:04<00:47,  3.86it/s]Validation Reasoning:
YES

Average Metric: 9.00 / 9 (100.0%):   5%|▍         | 9/192 [00:05<01:33,  1.96it/s]Validation Reasoning:
YES

Average Metric: 10.00 / 10 (100.0%):   5%|▌         | 10/192 [00:05<01:33,  1.95it/s]Validation Reasoning:
YES

Average Metric: 11.00 / 11 (100.0%):   5%|▌         | 10/192 [00:05<01:33,  1.95it/s]Validation Reasoning:
YES

Average Metric: 12.00 / 12 (100.0%):   6%|▋         | 12/192 [00:06<01:10,  2.56it/s]Validation Reasoning:
YES

Average Metric: 13.00 / 13 (100.0%):   7%|▋         | 13/192 [00:06<00:59,  3.01it/s]Validation Reasoning:
YES

Average Metric: 14.00 / 14 (100.0%):   7%|▋         | 14/192 [00:06<00:51,  3.45it/s]Validation Reasoning:
YES

Average Metric: 15.00 / 15 (100.0%):   8%|▊         | 15/192 [00:07<01:16,  2.32it/s]Validation Reasoning:
YES

Average Metric: 16.00 / 16 (100.0%):   8%|▊         | 16/192 [00:07<01:02,  2.80it/s]Validation Reasoning:
YES

Average Metric: 17.00 / 17 (100.0%):   9%|▉         | 17/192 [00:08<01:42,  1.71it/s]Validation Reasoning:
YES

Average Metric: 18.00 / 18 (100.0%):   9%|▉         | 18/192 [00:09<01:42,  1.70it/s]Validation Reasoning:
YES

Average Metric: 19.00 / 19 (100.0%):  10%|▉         | 19/192 [00:09<01:21,  2.13it/s]Validation Reasoning:
YES

Average Metric: 20.00 / 20 (100.0%):  10%|█         | 20/192 [00:09<01:05,  2.64it/s]Validation Reasoning:
YES

Average Metric: 21.00 / 21 (100.0%):  11%|█         | 21/192 [00:09<00:59,  2.89it/s]Validation Reasoning:
YES

Average Metric: 22.00 / 22 (100.0%):  11%|█▏        | 22/192 [00:10<00:50,  3.38it/s]Validation Reasoning:
YES

Average Metric: 23.00 / 23 (100.0%):  12%|█▏        | 23/192 [00:10<01:05,  2.56it/s]Validation Reasoning:
YES

Average Metric: 24.00 / 24 (100.0%):  12%|█▎        | 24/192 [00:11<01:19,  2.10it/s]Validation Reasoning:
YES

Average Metric: 25.00 / 25 (100.0%):  13%|█▎        | 25/192 [00:12<01:32,  1.80it/s]Validation Reasoning:
YES

Average Metric: 26.00 / 26 (100.0%):  13%|█▎        | 25/192 [00:12<01:32,  1.80it/s]Validation Reasoning:
YES

Average Metric: 27.00 / 27 (100.0%):  14%|█▍        | 27/192 [00:13<01:27,  1.90it/s]Validation Reasoning:
NO

Average Metric: 27.00 / 28 (96.4%):  15%|█▍        | 28/192 [00:13<01:22,  1.99it/s] Validation Reasoning:
YES

Average Metric: 28.00 / 29 (96.6%):  15%|█▌        | 29/192 [00:14<01:30,  1.80it/s]Validation Reasoning:
YES

Average Metric: 29.00 / 30 (96.7%):  16%|█▌        | 30/192 [00:14<01:31,  1.77it/s]Validation Reasoning:
YES

Average Metric: 30.00 / 31 (96.8%):  16%|█▌        | 31/192 [00:15<01:17,  2.08it/s]Validation Reasoning:
YES

Average Metric: 31.00 / 32 (96.9%):  17%|█▋        | 32/192 [00:16<01:44,  1.53it/s]Validation Reasoning:
YES

Average Metric: 32.00 / 33 (97.0%):  17%|█▋        | 32/192 [00:16<01:44,  1.53it/s]Validation Reasoning:
YES

Average Metric: 33.00 / 34 (97.1%):  17%|█▋        | 33/192 [00:16<01:28,  1.80it/s]Validation Reasoning:
YES

Average Metric: 34.00 / 35 (97.1%):  18%|█▊        | 35/192 [00:17<01:08,  2.31it/s]Validation Reasoning:
YES

Average Metric: 35.00 / 36 (97.2%):  19%|█▉        | 36/192 [00:17<01:23,  1.87it/s]Validation Reasoning:
YES

Average Metric: 36.00 / 37 (97.3%):  19%|█▉        | 37/192 [00:18<01:15,  2.04it/s]Validation Reasoning:
YES

Average Metric: 37.00 / 38 (97.4%):  20%|█▉        | 38/192 [00:18<01:06,  2.32it/s]Validation Reasoning:
YES

Average Metric: 38.00 / 39 (97.4%):  20%|██        | 39/192 [00:18<00:56,  2.73it/s]Validation Reasoning:
NO

Average Metric: 38.00 / 40 (95.0%):  21%|██        | 40/192 [00:19<00:51,  2.96it/s]Validation Reasoning:
YES

Average Metric: 39.00 / 41 (95.1%):  21%|██▏       | 41/192 [00:19<00:58,  2.57it/s]Validation Reasoning:
YES

Average Metric: 40.00 / 42 (95.2%):  22%|██▏       | 42/192 [00:20<01:26,  1.74it/s]Validation Reasoning:
YES

Average Metric: 41.00 / 43 (95.3%):  22%|██▏       | 43/192 [00:20<01:15,  1.96it/s]Validation Reasoning:
YES

Average Metric: 42.00 / 44 (95.5%):  23%|██▎       | 44/192 [00:21<01:20,  1.83it/s]Validation Reasoning:
YES

Average Metric: 43.00 / 45 (95.6%):  23%|██▎       | 44/192 [00:21<01:20,  1.83it/s]Validation Reasoning:
YES

Average Metric: 44.00 / 46 (95.7%):  24%|██▍       | 46/192 [00:21<00:47,  3.06it/s]Validation Reasoning:
YES

Average Metric: 45.00 / 47 (95.7%):  24%|██▍       | 46/192 [00:21<00:47,  3.06it/s]Validation Reasoning:
YES

Average Metric: 46.00 / 48 (95.8%):  25%|██▌       | 48/192 [00:23<01:14,  1.94it/s]Validation Reasoning:
NO

Average Metric: 46.00 / 49 (93.9%):  26%|██▌       | 49/192 [00:24<01:33,  1.53it/s]Validation Reasoning:
YES

Average Metric: 47.00 / 50 (94.0%):  26%|██▌       | 50/192 [00:24<01:16,  1.87it/s]Validation Reasoning:
YES

Average Metric: 48.00 / 51 (94.1%):  26%|██▌       | 50/192 [00:24<01:16,  1.87it/s]Validation Reasoning:
YES

Average Metric: 49.00 / 52 (94.2%):  27%|██▋       | 52/192 [00:24<00:49,  2.86it/s]Validation Reasoning:
YES

Average Metric: 50.00 / 53 (94.3%):  28%|██▊       | 53/192 [00:25<00:46,  3.01it/s]Validation Reasoning:
NO

Average Metric: 50.00 / 54 (92.6%):  28%|██▊       | 54/192 [00:26<01:18,  1.75it/s]Validation Reasoning:
YES

Average Metric: 51.00 / 55 (92.7%):  29%|██▊       | 55/192 [00:27<01:25,  1.61it/s]Validation Reasoning:
YES

Average Metric: 52.00 / 56 (92.9%):  29%|██▉       | 56/192 [00:27<01:23,  1.63it/s]Validation Reasoning:
YES

Average Metric: 53.00 / 57 (93.0%):  29%|██▉       | 56/192 [00:27<01:23,  1.63it/s]Validation Reasoning:
YES

Average Metric: 54.00 / 58 (93.1%):  30%|███       | 58/192 [00:27<00:50,  2.65it/s]Validation Reasoning:
YES

Average Metric: 55.00 / 59 (93.2%):  31%|███       | 59/192 [00:28<01:08,  1.94it/s]Validation Reasoning:
YES

Average Metric: 56.00 / 60 (93.3%):  31%|███▏      | 60/192 [00:29<01:02,  2.10it/s]Validation Reasoning:
YES

Average Metric: 57.00 / 61 (93.4%):  32%|███▏      | 61/192 [00:29<01:09,  1.88it/s]Validation Reasoning:
YES

Average Metric: 58.00 / 62 (93.5%):  32%|███▏      | 62/192 [00:30<00:57,  2.28it/s]Validation Reasoning:
YES

Average Metric: 59.00 / 63 (93.7%):  33%|███▎      | 63/192 [00:30<00:57,  2.23it/s]Validation Reasoning:
YES

Average Metric: 60.00 / 64 (93.8%):  33%|███▎      | 63/192 [00:30<00:57,  2.23it/s]Validation Reasoning:
YES

Average Metric: 61.00 / 65 (93.8%):  34%|███▍      | 65/192 [00:31<01:01,  2.08it/s]Validation Reasoning:
YES

Average Metric: 62.00 / 66 (93.9%):  34%|███▍      | 66/192 [00:31<00:55,  2.29it/s]Validation Reasoning:
YES

Average Metric: 63.00 / 67 (94.0%):  35%|███▍      | 67/192 [00:32<00:56,  2.22it/s]Validation Reasoning:
YES

Average Metric: 64.00 / 68 (94.1%):  35%|███▍      | 67/192 [00:32<00:56,  2.22it/s]Validation Reasoning:
YES

Average Metric: 65.00 / 69 (94.2%):  36%|███▌      | 69/192 [00:32<00:40,  3.05it/s]Validation Reasoning:
YES

Average Metric: 66.00 / 70 (94.3%):  36%|███▌      | 69/192 [00:32<00:40,  3.05it/s]Validation Reasoning:
NO

Average Metric: 66.00 / 71 (93.0%):  37%|███▋      | 71/192 [00:33<00:39,  3.09it/s]Validation Reasoning:
YES

Average Metric: 67.00 / 72 (93.1%):  37%|███▋      | 71/192 [00:34<00:39,  3.09it/s]Validation Reasoning:
YES

Average Metric: 67.00 / 72 (93.1%):  38%|███▊      | 72/192 [00:34<01:08,  1.75it/s]Validation Reasoning:
YES

Average Metric: 69.00 / 74 (93.2%):  39%|███▊      | 74/192 [00:34<00:44,  2.66it/s]Validation Reasoning:
YES

Average Metric: 70.00 / 75 (93.3%):  39%|███▉      | 75/192 [00:35<00:47,  2.49it/s]Validation Reasoning:
YES

Average Metric: 71.00 / 76 (93.4%):  39%|███▉      | 75/192 [00:35<00:47,  2.49it/s]Validation Reasoning:
YES

Average Metric: 72.00 / 77 (93.5%):  40%|████      | 77/192 [00:35<00:31,  3.65it/s]Validation Reasoning:
NO

Average Metric: 72.00 / 78 (92.3%):  41%|████      | 78/192 [00:35<00:33,  3.40it/s]Validation Reasoning:
YES

Average Metric: 73.00 / 79 (92.4%):  41%|████      | 79/192 [00:37<00:56,  1.99it/s]Validation Reasoning:
YES

Average Metric: 74.00 / 80 (92.5%):  42%|████▏     | 80/192 [00:37<00:56,  1.97it/s]Validation Reasoning:
YES

Average Metric: 75.00 / 81 (92.6%):  42%|████▏     | 81/192 [00:37<00:45,  2.46it/s]Validation Reasoning:
NO

Average Metric: 75.00 / 82 (91.5%):  42%|████▏     | 81/192 [00:37<00:45,  2.46it/s]Validation Reasoning:
YES

Average Metric: 76.00 / 83 (91.6%):  43%|████▎     | 83/192 [00:38<00:32,  3.34it/s]Validation Reasoning:
YES

Average Metric: 77.00 / 84 (91.7%):  43%|████▎     | 83/192 [00:38<00:32,  3.34it/s]Validation Reasoning:
YES

Average Metric: 78.00 / 85 (91.8%):  44%|████▍     | 85/192 [00:39<00:58,  1.82it/s]Validation Reasoning:
YES

Average Metric: 79.00 / 86 (91.9%):  45%|████▍     | 86/192 [00:40<00:51,  2.04it/s]Validation Reasoning:
YES

Average Metric: 80.00 / 87 (92.0%):  45%|████▌     | 87/192 [00:40<00:44,  2.37it/s]Validation Reasoning:
YES

Average Metric: 81.00 / 88 (92.0%):  45%|████▌     | 87/192 [00:40<00:44,  2.37it/s]Validation Reasoning:
YES

Average Metric: 82.00 / 89 (92.1%):  46%|████▋     | 89/192 [00:40<00:29,  3.48it/s]Validation Reasoning:
YES

Average Metric: 83.00 / 90 (92.2%):  47%|████▋     | 90/192 [00:41<00:37,  2.70it/s]Validation Reasoning:
YES

Average Metric: 84.00 / 91 (92.3%):  47%|████▋     | 90/192 [00:41<00:37,  2.70it/s]Validation Reasoning:
YES

Average Metric: 85.00 / 92 (92.4%):  48%|████▊     | 92/192 [00:42<00:46,  2.13it/s]Validation Reasoning:
YES

Average Metric: 86.00 / 93 (92.5%):  48%|████▊     | 93/192 [00:42<00:41,  2.38it/s]Validation Reasoning:
YES

Average Metric: 87.00 / 94 (92.6%):  48%|████▊     | 93/192 [00:42<00:41,  2.38it/s]Validation Reasoning:
YES

Average Metric: 88.00 / 95 (92.6%):  49%|████▉     | 95/192 [00:43<00:35,  2.72it/s]Validation Reasoning:
YES

Average Metric: 89.00 / 96 (92.7%):  50%|█████     | 96/192 [00:43<00:32,  2.97it/s]Validation Reasoning:
YES

Average Metric: 90.00 / 97 (92.8%):  50%|█████     | 96/192 [00:43<00:32,  2.97it/s]Validation Reasoning:
NO

Average Metric: 90.00 / 98 (91.8%):  51%|█████     | 98/192 [00:43<00:24,  3.82it/s]Validation Reasoning:
YES

Average Metric: 91.00 / 99 (91.9%):  52%|█████▏    | 99/192 [00:45<00:45,  2.03it/s]Validation Reasoning:
YES

Average Metric: 92.00 / 100 (92.0%):  52%|█████▏    | 100/192 [00:45<00:37,  2.48it/s]Validation Reasoning:
YES

Average Metric: 93.00 / 101 (92.1%):  53%|█████▎    | 101/192 [00:45<00:33,  2.69it/s]Validation Reasoning:
YES

Average Metric: 94.00 / 102 (92.2%):  53%|█████▎    | 101/192 [00:45<00:33,  2.69it/s]Validation Reasoning:
NO

Average Metric: 94.00 / 103 (91.3%):  54%|█████▎    | 103/192 [00:46<00:36,  2.41it/s]Validation Reasoning:
YES

Average Metric: 95.00 / 104 (91.3%):  54%|█████▍    | 104/192 [00:46<00:37,  2.35it/s]Validation Reasoning:
YES

Average Metric: 96.00 / 105 (91.4%):  55%|█████▍    | 105/192 [00:47<00:46,  1.86it/s]Validation Reasoning:
YES

Average Metric: 97.00 / 106 (91.5%):  55%|█████▍    | 105/192 [00:47<00:46,  1.86it/s]Validation Reasoning:
YES

Average Metric: 98.00 / 107 (91.6%):  56%|█████▌    | 107/192 [00:47<00:29,  2.89it/s]Validation Reasoning:
YES

Average Metric: 99.00 / 108 (91.7%):  56%|█████▋    | 108/192 [00:48<00:25,  3.33it/s]Validation Reasoning:
YES

Average Metric: 100.00 / 109 (91.7%):  56%|█████▋    | 108/192 [00:48<00:25,  3.33it/s]Validation Reasoning:
YES

Average Metric: 101.00 / 110 (91.8%):  57%|█████▋    | 110/192 [00:48<00:25,  3.16it/s]Validation Reasoning:
YES

Average Metric: 102.00 / 111 (91.9%):  58%|█████▊    | 111/192 [00:48<00:23,  3.48it/s]Validation Reasoning:
YES

Average Metric: 103.00 / 112 (92.0%):  58%|█████▊    | 112/192 [00:49<00:29,  2.71it/s]Validation Reasoning:
NO

Average Metric: 103.00 / 113 (91.2%):  59%|█████▉    | 113/192 [00:50<00:31,  2.49it/s]Validation Reasoning:
YES

Average Metric: 104.00 / 114 (91.2%):  59%|█████▉    | 114/192 [00:50<00:29,  2.68it/s]Validation Reasoning:
YES

Average Metric: 105.00 / 115 (91.3%):  59%|█████▉    | 114/192 [00:50<00:29,  2.68it/s]Validation Reasoning:
YES

Average Metric: 106.00 / 116 (91.4%):  60%|██████    | 116/192 [00:50<00:20,  3.76it/s]Validation Reasoning:
YES

Average Metric: 107.00 / 117 (91.5%):  61%|██████    | 117/192 [00:51<00:30,  2.47it/s]Validation Reasoning:
YES

Average Metric: 108.00 / 118 (91.5%):  61%|██████▏   | 118/192 [00:51<00:26,  2.78it/s]Validation Reasoning:
YES

Average Metric: 109.00 / 119 (91.6%):  62%|██████▏   | 119/192 [00:51<00:23,  3.17it/s]Validation Reasoning:
YES

Average Metric: 110.00 / 120 (91.7%):  62%|██████▎   | 120/192 [00:52<00:30,  2.36it/s]Validation Reasoning:
YES

Average Metric: 111.00 / 121 (91.7%):  63%|██████▎   | 121/192 [00:52<00:24,  2.87it/s]Validation Reasoning:
YES

Average Metric: 112.00 / 122 (91.8%):  64%|██████▎   | 122/192 [00:53<00:25,  2.77it/s]Validation Reasoning:
YES

Average Metric: 113.00 / 123 (91.9%):  64%|██████▍   | 123/192 [00:53<00:25,  2.74it/s]Validation Reasoning:
YES

Average Metric: 114.00 / 124 (91.9%):  65%|██████▍   | 124/192 [00:54<00:41,  1.66it/s]Validation Reasoning:
YES

Average Metric: 115.00 / 125 (92.0%):  65%|██████▍   | 124/192 [00:54<00:41,  1.66it/s]Validation Reasoning:
YES

Average Metric: 116.00 / 126 (92.1%):  66%|██████▌   | 126/192 [00:54<00:23,  2.77it/s]Validation Reasoning:
YES

Average Metric: 117.00 / 127 (92.1%):  66%|██████▌   | 126/192 [00:54<00:23,  2.77it/s]Validation Reasoning:
YES

Average Metric: 118.00 / 128 (92.2%):  67%|██████▋   | 128/192 [00:55<00:17,  3.74it/s]Validation Reasoning:
YES

Average Metric: 119.00 / 129 (92.2%):  67%|██████▋   | 129/192 [00:55<00:19,  3.28it/s]Validation Reasoning:
YES

Average Metric: 120.00 / 130 (92.3%):  67%|██████▋   | 129/192 [00:55<00:19,  3.28it/s]Validation Reasoning:
YES

Average Metric: 121.00 / 131 (92.4%):  68%|██████▊   | 131/192 [00:56<00:16,  3.59it/s]Validation Reasoning:
YES

Average Metric: 122.00 / 132 (92.4%):  69%|██████▉   | 132/192 [00:57<00:27,  2.17it/s]Validation Reasoning:
YES

Average Metric: 123.00 / 133 (92.5%):  69%|██████▉   | 133/192 [00:58<00:34,  1.70it/s]Validation Reasoning:
YES

Average Metric: 124.00 / 134 (92.5%):  70%|██████▉   | 134/192 [00:58<00:29,  1.95it/s]Validation Reasoning:
YES

Average Metric: 125.00 / 135 (92.6%):  70%|███████   | 135/192 [00:58<00:23,  2.42it/s]Validation Reasoning:
YES

Average Metric: 126.00 / 136 (92.6%):  71%|███████   | 136/192 [00:58<00:18,  2.99it/s]Validation Reasoning:
YES

Average Metric: 127.00 / 137 (92.7%):  71%|███████▏  | 137/192 [00:59<00:18,  2.98it/s]Validation Reasoning:
YES

Average Metric: 128.00 / 138 (92.8%):  71%|███████▏  | 137/192 [00:59<00:18,  2.98it/s]Validation Reasoning:
YES

Average Metric: 129.00 / 139 (92.8%):  72%|███████▏  | 139/192 [00:59<00:19,  2.67it/s]Validation Reasoning:
YES

Average Metric: 130.00 / 140 (92.9%):  73%|███████▎  | 140/192 [01:00<00:17,  3.01it/s]Validation Reasoning:
YES

Average Metric: 131.00 / 141 (92.9%):  73%|███████▎  | 141/192 [01:00<00:21,  2.39it/s]Validation Reasoning:
YES

Average Metric: 132.00 / 142 (93.0%):  74%|███████▍  | 142/192 [01:00<00:17,  2.92it/s]Validation Reasoning:
YES

Average Metric: 133.00 / 143 (93.0%):  74%|███████▍  | 143/192 [01:01<00:18,  2.72it/s]Validation Reasoning:
YES

Average Metric: 134.00 / 144 (93.1%):  75%|███████▌  | 144/192 [01:01<00:14,  3.32it/s]Validation Reasoning:
YES

Average Metric: 135.00 / 145 (93.1%):  76%|███████▌  | 145/192 [01:02<00:18,  2.52it/s]Validation Reasoning:
YES

Average Metric: 136.00 / 146 (93.2%):  76%|███████▌  | 146/192 [01:02<00:20,  2.21it/s]Validation Reasoning:
YES

Average Metric: 137.00 / 147 (93.2%):  77%|███████▋  | 147/192 [01:03<00:19,  2.33it/s]Validation Reasoning:
YES

Average Metric: 138.00 / 148 (93.2%):  77%|███████▋  | 148/192 [01:03<00:19,  2.25it/s]Validation Reasoning:
YES

Average Metric: 139.00 / 149 (93.3%):  78%|███████▊  | 149/192 [01:03<00:18,  2.31it/s]Validation Reasoning:
YES

Average Metric: 140.00 / 150 (93.3%):  78%|███████▊  | 149/192 [01:03<00:18,  2.31it/s]Validation Reasoning:
YES

Average Metric: 141.00 / 151 (93.4%):  79%|███████▊  | 151/192 [01:04<00:10,  3.80it/s]Validation Reasoning:
NO

Average Metric: 141.00 / 152 (92.8%):  79%|███████▉  | 152/192 [01:04<00:16,  2.42it/s]Validation Reasoning:
YES

Average Metric: 142.00 / 153 (92.8%):  80%|███████▉  | 153/192 [01:05<00:16,  2.41it/s]Validation Reasoning:
YES

Average Metric: 143.00 / 154 (92.9%):  80%|████████  | 154/192 [01:05<00:12,  2.94it/s]Validation Reasoning:
YES

Average Metric: 144.00 / 155 (92.9%):  81%|████████  | 155/192 [01:06<00:18,  1.95it/s]Validation Reasoning:
YES

Average Metric: 145.00 / 156 (92.9%):  81%|████████▏ | 156/192 [01:07<00:15,  2.28it/s]Validation Reasoning:
YES

Average Metric: 146.00 / 157 (93.0%):  82%|████████▏ | 157/192 [01:07<00:20,  1.74it/s]Validation Reasoning:
YES

Average Metric: 147.00 / 158 (93.0%):  82%|████████▏ | 158/192 [01:07<00:16,  2.09it/s]Validation Reasoning:
YES

Average Metric: 148.00 / 159 (93.1%):  82%|████████▏ | 158/192 [01:07<00:16,  2.09it/s]Validation Reasoning:
YES

Average Metric: 149.00 / 160 (93.1%):  83%|████████▎ | 160/192 [01:08<00:09,  3.30it/s]Validation Reasoning:
YES

Average Metric: 150.00 / 161 (93.2%):  83%|████████▎ | 160/192 [01:08<00:09,  3.30it/s]Validation Reasoning:
YES

Average Metric: 151.00 / 162 (93.2%):  84%|████████▍ | 162/192 [01:09<00:16,  1.80it/s]Validation Reasoning:
YES

Average Metric: 152.00 / 163 (93.3%):  85%|████████▍ | 163/192 [01:10<00:15,  1.92it/s]Validation Reasoning:
YES

Average Metric: 153.00 / 164 (93.3%):  85%|████████▍ | 163/192 [01:10<00:15,  1.92it/s]Validation Reasoning:
YES

Average Metric: 154.00 / 165 (93.3%):  86%|████████▌ | 165/192 [01:10<00:09,  2.87it/s]Validation Reasoning:
YES

Average Metric: 155.00 / 166 (93.4%):  86%|████████▋ | 166/192 [01:10<00:07,  3.39it/s]Validation Reasoning:
YES

Average Metric: 156.00 / 167 (93.4%):  87%|████████▋ | 167/192 [01:10<00:07,  3.55it/s]Validation Reasoning:
NO

Average Metric: 156.00 / 168 (92.9%):  87%|████████▋ | 167/192 [01:10<00:07,  3.55it/s]Validation Reasoning:
YES

Average Metric: 157.00 / 169 (92.9%):  88%|████████▊ | 169/192 [01:11<00:06,  3.67it/s]Validation Reasoning:
YES

Average Metric: 158.00 / 170 (92.9%):  89%|████████▊ | 170/192 [01:12<00:11,  1.91it/s]Validation Reasoning:
YES

Average Metric: 159.00 / 171 (93.0%):  89%|████████▉ | 171/192 [01:12<00:08,  2.34it/s]Validation Reasoning:
YES

Average Metric: 160.00 / 172 (93.0%):  89%|████████▉ | 171/192 [01:12<00:08,  2.34it/s]Validation Reasoning:
YES

Average Metric: 161.00 / 173 (93.1%):  90%|█████████ | 173/192 [01:13<00:06,  2.97it/s]Validation Reasoning:
YES

Average Metric: 162.00 / 174 (93.1%):  91%|█████████ | 174/192 [01:13<00:05,  3.51it/s]Validation Reasoning:
YES

Average Metric: 163.00 / 175 (93.1%):  91%|█████████ | 175/192 [01:13<00:04,  3.57it/s]Validation Reasoning:
YES

Average Metric: 164.00 / 176 (93.2%):  91%|█████████ | 175/192 [01:13<00:04,  3.57it/s]Validation Reasoning:
YES

Average Metric: 165.00 / 177 (93.2%):  92%|█████████▏| 177/192 [01:14<00:06,  2.47it/s]Validation Reasoning:
NO


2025/05/01 02:15:08 INFO dspy.evaluate.evaluate: Average Metric: 179 / 192 (93.2%)

Scores so far: [57.29, 94.27, 95.83, 90.1, 93.23]
Best score so far: 95.83

  1%|          | 1/192 [00:02<08:57,  2.81s/it]

Validation Reasoning:
YES

Bootstrapped 1 full traces after 1 examples for up to 1 rounds, amounting to 1 attempts.
  0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Average Metric: 1.00 / 1 (100.0%):   1%|          | 1/192 [00:02<09:04,  2.85s/it]Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 1/192 [00:02<09:04,  2.85s/it]Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   2%|▏         | 3/192 [00:03<02:33,  1.23it/s]Validation Reasoning:
YES

Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 3/192 [00:03<02:33,  1.23it/s]Validation Reasoning:
YES

Average Metric: 5.00 / 5 (100.0%):   3%|▎         | 5/192 [00:03<01:23,  2.24it/s]Validation Reasoning:
YES

Average Metric: 6.00 / 6 (100.0%):   3%|▎         | 6/192 [00:03<01:15,  2.46it/s]Validation Reasoning:
YES

Average Metric: 7.00 / 7 (100.0%):   3%|▎         | 6/192 [00:03<01:15,  2.46it/s]Validation Reasoning:
YES

Average Metric: 8.00 / 8 (100.0%):   4%|▍         | 8/192 [00:05<02:03,  1.49it/s]Validation Reasoning:
YES

Average Metric: 9.00 / 9 (100.0%):   4%|▍         | 8/192 [00:05<02:03,  1.49it/s]Validation Reasoning:
YES

Average Metric: 10.00 / 10 (100.0%):   5%|▍         | 9/192 [00:05<01:38,  1.87it/s]Validation Reasoning:
YES

Average Metric: 11.00 / 11 (100.0%):   6%|▌         | 11/192 [00:05<01:06,  2.74it/s]Validation Reasoning:
YES

Average Metric: 12.00 / 12 (100.0%):   6%|▋         | 12/192 [00:06<00:58,  3.06it/s]Validation Reasoning:
YES

Average Metric: 13.00 / 13 (100.0%):   7%|▋         | 13/192 [00:06<00:49,  3.63it/s]Validation Reasoning:
YES

Average Metric: 14.00 / 14 (100.0%):   7%|▋         | 13/192 [00:06<00:49,  3.63it/s]Validation Reasoning:
YES

Average Metric: 15.00 / 15 (100.0%):   7%|▋         | 14/192 [00:06<00:46,  3.83it/s]Validation Reasoning:
YES

Average Metric: 16.00 / 16 (100.0%):   8%|▊         | 16/192 [00:08<01:25,  2.05it/s]Validation Reasoning:
YES

Average Metric: 17.00 / 17 (100.0%):   9%|▉         | 17/192 [00:08<01:22,  2.13it/s]Validation Reasoning:
YES

Average Metric: 18.00 / 18 (100.0%):   9%|▉         | 17/192 [00:09<01:22,  2.13it/s]Validation Reasoning:
YES

Validation Reasoning:
YES

Validation Reasoning:
YES

Average Metric: 21.00 / 21 (100.0%):  10%|█         | 20/192 [00:09<01:33,  1.83it/s]Validation Reasoning:
YES

Average Metric: 22.00 / 22 (100.0%):  11%|█▏        | 22/192 [00:10<00:51,  3.29it/s]Validation Reasoning:
YES

Average Metric: 23.00 / 23 (100.0%):  12%|█▏        | 23/192 [00:10<00:51,  3.28it/s]Validation Reasoning:
YES

Average Metric: 24.00 / 24 (100.0%):  12%|█▎        | 24/192 [00:12<01:54,  1.46it/s]Validation Reasoning:
YES

Average Metric: 25.00 / 25 (100.0%):  12%|█▎        | 24/192 [00:12<01:54,  1.46it/s]Validation Reasoning:
YES

Average Metric: 26.00 / 26 (100.0%):  14%|█▎        | 26/192 [00:12<01:21,  2.04it/s]Validation Reasoning:
YES

Average Metric: 27.00 / 27 (100.0%):  14%|█▎        | 26/192 [00:12<01:21,  2.04it/s]Validation Reasoning:
YES

Average Metric: 28.00 / 28 (100.0%):  15%|█▍        | 28/192 [00:13<00:54,  2.99it/s]Validation Reasoning:
YES

Average Metric: 29.00 / 29 (100.0%):  15%|█▍        | 28/192 [00:13<00:54,  2.99it/s]Validation Reasoning:
YES

Average Metric: 30.00 / 30 (100.0%):  16%|█▌        | 30/192 [00:15<01:39,  1.63it/s]Validation Reasoning:
YES

Average Metric: 31.00 / 31 (100.0%):  16%|█▌        | 30/192 [00:15<01:39,  1.63it/s]Validation Reasoning:
YES

Average Metric: 32.00 / 32 (100.0%):  17%|█▋        | 32/192 [00:15<01:10,  2.28it/s]Validation Reasoning:
YES

Average Metric: 33.00 / 33 (100.0%):  17%|█▋        | 32/192 [00:15<01:10,  2.28it/s]Validation Reasoning:
YES

Average Metric: 34.00 / 34 (100.0%):  18%|█▊        | 34/192 [00:15<00:55,  2.83it/s]Validation Reasoning:
YES

Average Metric: 35.00 / 35 (100.0%):  18%|█▊        | 35/192 [00:15<00:49,  3.16it/s]Validation Reasoning:
YES

Average Metric: 36.00 / 36 (100.0%):  19%|█▉        | 36/192 [00:17<01:39,  1.56it/s]Validation Reasoning:
YES

Average Metric: 37.00 / 37 (100.0%):  19%|█▉        | 37/192 [00:18<01:22,  1.87it/s]Validation Reasoning:
YES

Average Metric: 38.00 / 38 (100.0%):  20%|█▉        | 38/192 [00:18<01:11,  2.16it/s]Validation Reasoning:
YES

Average Metric: 39.00 / 39 (100.0%):  20%|██        | 39/192 [00:18<00:56,  2.71it/s]Validation Reasoning:
YES

Average Metric: 40.00 / 40 (100.0%):  21%|██        | 40/192 [00:18<00:45,  3.36it/s]Validation Reasoning:
YES

Average Metric: 41.00 / 41 (100.0%):  21%|██▏       | 41/192 [00:19<01:24,  1.78it/s]Validation Reasoning:
NO

Average Metric: 41.00 / 42 (97.6%):  21%|██▏       | 41/192 [00:19<01:24,  1.78it/s] Validation Reasoning:
YES

Average Metric: 42.00 / 43 (97.7%):  22%|██▏       | 43/192 [00:20<01:19,  1.87it/s]Validation Reasoning:
YES

Average Metric: 43.00 / 44 (97.7%):  23%|██▎       | 44/192 [00:21<01:20,  1.83it/s]Validation Reasoning:
YES

Average Metric: 44.00 / 45 (97.8%):  23%|██▎       | 45/192 [00:21<01:11,  2.05it/s]Validation Reasoning:
YES

Average Metric: 45.00 / 46 (97.8%):  24%|██▍       | 46/192 [00:22<01:14,  1.97it/s]Validation Reasoning:
YES

Average Metric: 46.00 / 47 (97.9%):  24%|██▍       | 46/192 [00:22<01:14,  1.97it/s]Validation Reasoning:
YES

Average Metric: 47.00 / 48 (97.9%):  25%|██▌       | 48/192 [00:22<00:52,  2.74it/s]Validation Reasoning:
YES

Average Metric: 48.00 / 49 (98.0%):  26%|██▌       | 49/192 [00:23<01:22,  1.73it/s]Validation Reasoning:
YES

Average Metric: 49.00 / 50 (98.0%):  26%|██▌       | 50/192 [00:24<01:08,  2.07it/s]Validation Reasoning:
YES

Average Metric: 50.00 / 51 (98.0%):  27%|██▋       | 51/192 [00:24<00:54,  2.60it/s]Validation Reasoning:
YES

Average Metric: 51.00 / 52 (98.1%):  27%|██▋       | 52/192 [00:24<00:50,  2.75it/s]Validation Reasoning:
YES

Average Metric: 52.00 / 53 (98.1%):  28%|██▊       | 53/192 [00:24<00:55,  2.49it/s]Validation Reasoning:
YES

Average Metric: 53.00 / 54 (98.1%):  28%|██▊       | 54/192 [00:26<01:40,  1.38it/s]Validation Reasoning:
YES

Average Metric: 54.00 / 55 (98.2%):  28%|██▊       | 54/192 [00:26<01:40,  1.38it/s]Validation Reasoning:
YES

Average Metric: 55.00 / 56 (98.2%):  29%|██▉       | 56/192 [00:26<01:04,  2.11it/s]Validation Reasoning:
YES

Average Metric: 56.00 / 57 (98.2%):  30%|██▉       | 57/192 [00:27<01:00,  2.24it/s]Validation Reasoning:
YES

Average Metric: 57.00 / 58 (98.3%):  30%|███       | 58/192 [00:27<00:48,  2.74it/s]Validation Reasoning:
YES

Average Metric: 58.00 / 59 (98.3%):  30%|███       | 58/192 [00:27<00:48,  2.74it/s]Validation Reasoning:
YES

Average Metric: 59.00 / 60 (98.3%):  31%|███▏      | 60/192 [00:28<01:09,  1.91it/s]Validation Reasoning:
YES

Average Metric: 60.00 / 61 (98.4%):  32%|███▏      | 61/192 [00:29<01:03,  2.06it/s]Validation Reasoning:
YES

Average Metric: 61.00 / 62 (98.4%):  32%|███▏      | 62/192 [00:29<00:55,  2.35it/s]Validation Reasoning:
YES

Average Metric: 62.00 / 63 (98.4%):  32%|███▏      | 62/192 [00:29<00:55,  2.35it/s]Validation Reasoning:
YES

Average Metric: 63.00 / 64 (98.4%):  33%|███▎      | 64/192 [00:30<00:49,  2.59it/s]Validation Reasoning:
YES

Average Metric: 64.00 / 65 (98.5%):  33%|███▎      | 64/192 [00:30<00:49,  2.59it/s]Validation Reasoning:
YES

Average Metric: 65.00 / 66 (98.5%):  34%|███▍      | 66/192 [00:30<00:38,  3.24it/s]Validation Reasoning:
YES

Average Metric: 66.00 / 67 (98.5%):  35%|███▍      | 67/192 [00:31<01:02,  1.99it/s]Validation Reasoning:
YES

Average Metric: 67.00 / 68 (98.5%):  35%|███▍      | 67/192 [00:31<01:02,  1.99it/s]Validation Reasoning:
YES

Average Metric: 68.00 / 69 (98.6%):  36%|███▌      | 69/192 [00:32<00:51,  2.41it/s]Validation Reasoning:
YES

Average Metric: 69.00 / 70 (98.6%):  36%|███▋      | 70/192 [00:32<00:45,  2.68it/s]Validation Reasoning:
YES

Average Metric: 70.00 / 71 (98.6%):  37%|███▋      | 71/192 [00:32<00:50,  2.39it/s]Validation Reasoning:
YES

Average Metric: 71.00 / 72 (98.6%):  38%|███▊      | 72/192 [00:33<00:49,  2.43it/s]Validation Reasoning:
YES

Average Metric: 72.00 / 73 (98.6%):  38%|███▊      | 73/192 [00:34<01:04,  1.83it/s]Validation Reasoning:
YES

Average Metric: 73.00 / 74 (98.6%):  39%|███▊      | 74/192 [00:34<00:50,  2.35it/s]Validation Reasoning:
YES

Average Metric: 74.00 / 75 (98.7%):  39%|███▉      | 75/192 [00:35<01:15,  1.55it/s]Validation Reasoning:
YES

Average Metric: 75.00 / 76 (98.7%):  39%|███▉      | 75/192 [00:35<01:15,  1.55it/s]Validation Reasoning:
YES

Average Metric: 76.00 / 77 (98.7%):  40%|████      | 77/192 [00:35<00:44,  2.57it/s]Validation Reasoning:
YES

Average Metric: 77.00 / 78 (98.7%):  41%|████      | 78/192 [00:35<00:40,  2.79it/s]Validation Reasoning:
YES

Average Metric: 78.00 / 79 (98.7%):  41%|████      | 79/192 [00:36<00:48,  2.32it/s]Validation Reasoning:
NO

Average Metric: 78.00 / 80 (97.5%):  42%|████▏     | 80/192 [00:37<01:03,  1.78it/s]Validation Reasoning:
YES

Average Metric: 79.00 / 81 (97.5%):  42%|████▏     | 81/192 [00:37<00:57,  1.93it/s]Validation Reasoning:
YES

Average Metric: 80.00 / 82 (97.6%):  43%|████▎     | 82/192 [00:38<00:44,  2.50it/s]Validation Reasoning:
YES

Average Metric: 81.00 / 83 (97.6%):  43%|████▎     | 83/192 [00:38<00:35,  3.09it/s]Validation Reasoning:
YES

Average Metric: 82.00 / 84 (97.6%):  44%|████▍     | 84/192 [00:38<00:35,  3.07it/s]Validation Reasoning:
YES

Average Metric: 83.00 / 85 (97.6%):  44%|████▍     | 85/192 [00:38<00:32,  3.30it/s]Validation Reasoning:
YES

Average Metric: 84.00 / 86 (97.7%):  45%|████▍     | 86/192 [00:39<00:54,  1.93it/s]Validation Reasoning:
YES

Average Metric: 85.00 / 87 (97.7%):  45%|████▌     | 87/192 [00:40<00:49,  2.12it/s]Validation Reasoning:
YES

Average Metric: 86.00 / 88 (97.7%):  45%|████▌     | 87/192 [00:40<00:49,  2.12it/s]Validation Reasoning:
YES

Average Metric: 87.00 / 89 (97.8%):  46%|████▋     | 89/192 [00:40<00:39,  2.62it/s]Validation Reasoning:
YES

Average Metric: 88.00 / 90 (97.8%):  47%|████▋     | 90/192 [00:40<00:36,  2.76it/s]Validation Reasoning:
YES

Average Metric: 89.00 / 91 (97.8%):  47%|████▋     | 91/192 [00:41<00:39,  2.56it/s]Validation Reasoning:
YES

Average Metric: 90.00 / 92 (97.8%):  48%|████▊     | 92/192 [00:42<00:57,  1.73it/s]Validation Reasoning:
YES

Average Metric: 91.00 / 93 (97.8%):  48%|████▊     | 92/192 [00:42<00:57,  1.73it/s]Validation Reasoning:
YES

Average Metric: 92.00 / 94 (97.9%):  49%|████▉     | 94/192 [00:42<00:34,  2.86it/s]Validation Reasoning:
YES

Average Metric: 93.00 / 95 (97.9%):  49%|████▉     | 94/192 [00:42<00:34,  2.86it/s]Validation Reasoning:
YES

Average Metric: 94.00 / 96 (97.9%):  49%|████▉     | 95/192 [00:43<00:32,  2.97it/s]Validation Reasoning:
YES

Average Metric: 95.00 / 97 (97.9%):  51%|█████     | 97/192 [00:43<00:36,  2.59it/s]Validation Reasoning:
YES

Average Metric: 96.00 / 98 (98.0%):  51%|█████     | 98/192 [00:44<00:37,  2.50it/s]Validation Reasoning:
YES

Average Metric: 97.00 / 99 (98.0%):  52%|█████▏    | 99/192 [00:44<00:34,  2.66it/s]Validation Reasoning:
YES

Average Metric: 98.00 / 100 (98.0%):  52%|█████▏    | 100/192 [00:45<00:49,  1.87it/s]Validation Reasoning:
YES

Average Metric: 99.00 / 101 (98.0%):  52%|█████▏    | 100/192 [00:45<00:49,  1.87it/s]Validation Reasoning:
YES

Average Metric: 100.00 / 102 (98.0%):  53%|█████▎    | 102/192 [00:45<00:33,  2.71it/s]Validation Reasoning:
NO

Average Metric: 100.00 / 103 (97.1%):  54%|█████▎    | 103/192 [00:46<00:35,  2.48it/s]Validation Reasoning:
YES

Average Metric: 101.00 / 104 (97.1%):  54%|█████▍    | 104/192 [00:46<00:29,  3.01it/s]Validation Reasoning:
YES

Average Metric: 102.00 / 105 (97.1%):  55%|█████▍    | 105/192 [00:46<00:31,  2.73it/s]Validation Reasoning:
YES

Average Metric: 103.00 / 106 (97.2%):  55%|█████▌    | 106/192 [00:47<00:26,  3.30it/s]Validation Reasoning:
YES

Average Metric: 104.00 / 107 (97.2%):  56%|█████▌    | 107/192 [00:47<00:21,  3.90it/s]Validation Reasoning:
YES

Average Metric: 105.00 / 108 (97.2%):  56%|█████▌    | 107/192 [00:48<00:21,  3.90it/s]Validation Reasoning:
YES
Average Metric: 105.00 / 108 (97.2%):  56%|█████▋    | 108/192 [00:48<00:51,  1.64it/s]
Validation Reasoning:
YES

Average Metric: 107.00 / 110 (97.3%):  57%|█████▋    | 109/192 [00:48<00:39,  2.08it/s]Validation Reasoning:
YES

Average Metric: 108.00 / 111 (97.3%):  58%|█████▊    | 111/192 [00:49<00:26,  3.05it/s]Validation Reasoning:
YES

Average Metric: 109.00 / 112 (97.3%):  58%|█████▊    | 112/192 [00:49<00:22,  3.49it/s]Validation Reasoning:
YES

Average Metric: 110.00 / 113 (97.3%):  59%|█████▉    | 113/192 [00:49<00:21,  3.61it/s]Validation Reasoning:
YES

Average Metric: 111.00 / 114 (97.4%):  59%|█████▉    | 114/192 [00:51<00:49,  1.56it/s]Validation Reasoning:
YES

Average Metric: 112.00 / 115 (97.4%):  59%|█████▉    | 114/192 [00:51<00:49,  1.56it/s]Validation Reasoning:
YES

Average Metric: 113.00 / 116 (97.4%):  60%|██████    | 116/192 [00:51<00:30,  2.52it/s]Validation Reasoning:
YES

Average Metric: 114.00 / 117 (97.4%):  61%|██████    | 117/192 [00:52<00:36,  2.08it/s]Validation Reasoning:
YES

Average Metric: 115.00 / 118 (97.5%):  61%|██████▏   | 118/192 [00:52<00:29,  2.55it/s]Validation Reasoning:
YES

Average Metric: 116.00 / 119 (97.5%):  62%|██████▏   | 119/192 [00:52<00:24,  2.94it/s]Validation Reasoning:
YES

Average Metric: 117.00 / 120 (97.5%):  62%|██████▎   | 120/192 [00:52<00:22,  3.24it/s]Validation Reasoning:
YES

Average Metric: 118.00 / 121 (97.5%):  63%|██████▎   | 121/192 [00:53<00:33,  2.11it/s]Validation Reasoning:
YES

Average Metric: 119.00 / 122 (97.5%):  64%|██████▎   | 122/192 [00:53<00:27,  2.52it/s]Validation Reasoning:
YES

Average Metric: 120.00 / 123 (97.6%):  64%|██████▍   | 123/192 [00:54<00:37,  1.83it/s]Validation Reasoning:
YES

Average Metric: 121.00 / 124 (97.6%):  64%|██████▍   | 123/192 [00:54<00:37,  1.83it/s]Validation Reasoning:
YES

Average Metric: 122.00 / 125 (97.6%):  65%|██████▌   | 125/192 [00:54<00:23,  2.88it/s]Validation Reasoning:
YES

Average Metric: 123.00 / 126 (97.6%):  65%|██████▌   | 125/192 [00:54<00:23,  2.88it/s]Validation Reasoning:
YES

Average Metric: 124.00 / 127 (97.6%):  66%|██████▌   | 127/192 [00:55<00:15,  4.10it/s]Validation Reasoning:
YES

Average Metric: 125.00 / 128 (97.7%):  67%|██████▋   | 128/192 [00:55<00:14,  4.39it/s]Validation Reasoning:
YES

Average Metric: 126.00 / 129 (97.7%):  67%|██████▋   | 129/192 [00:55<00:19,  3.29it/s]Validation Reasoning:
YES

Average Metric: 127.00 / 130 (97.7%):  68%|██████▊   | 130/192 [00:56<00:19,  3.26it/s]Validation Reasoning:
YES

Average Metric: 128.00 / 131 (97.7%):  68%|██████▊   | 131/192 [00:57<00:33,  1.79it/s]Validation Reasoning:
YES

Average Metric: 129.00 / 132 (97.7%):  68%|██████▊   | 131/192 [00:57<00:33,  1.79it/s]Validation Reasoning:
YES

Average Metric: 130.00 / 133 (97.7%):  69%|██████▉   | 133/192 [00:57<00:21,  2.72it/s]Validation Reasoning:
YES

Average Metric: 131.00 / 134 (97.8%):  70%|██████▉   | 134/192 [00:57<00:20,  2.83it/s]Validation Reasoning:
YES

Average Metric: 132.00 / 135 (97.8%):  70%|██████▉   | 134/192 [00:57<00:20,  2.83it/s]Validation Reasoning:
YES

Average Metric: 133.00 / 136 (97.8%):  70%|███████   | 135/192 [00:57<00:20,  2.83it/s]Validation Reasoning:
YES

Average Metric: 134.00 / 137 (97.8%):  71%|███████▏  | 137/192 [00:59<00:19,  2.80it/s]Validation Reasoning:
YES

Average Metric: 135.00 / 138 (97.8%):  72%|███████▏  | 138/192 [00:59<00:17,  3.10it/s]Validation Reasoning:
YES

Average Metric: 136.00 / 139 (97.8%):  72%|███████▏  | 139/192 [00:59<00:18,  2.88it/s]Validation Reasoning:
YES

Average Metric: 137.00 / 140 (97.9%):  73%|███████▎  | 140/192 [01:00<00:19,  2.68it/s]Validation Reasoning:
YES

Average Metric: 138.00 / 141 (97.9%):  73%|███████▎  | 140/192 [01:00<00:19,  2.68it/s]Validation Reasoning:
YES

Average Metric: 139.00 / 142 (97.9%):  74%|███████▍  | 142/192 [01:00<00:17,  2.93it/s]Validation Reasoning:
YES

Average Metric: 140.00 / 143 (97.9%):  74%|███████▍  | 143/192 [01:01<00:23,  2.07it/s]Validation Reasoning:
YES

Average Metric: 141.00 / 144 (97.9%):  74%|███████▍  | 143/192 [01:01<00:23,  2.07it/s]Validation Reasoning:
YES

Average Metric: 142.00 / 145 (97.9%):  76%|███████▌  | 145/192 [01:01<00:17,  2.75it/s]Validation Reasoning:
YES

Average Metric: 143.00 / 146 (97.9%):  76%|███████▌  | 146/192 [01:02<00:18,  2.51it/s]Validation Reasoning:
YES

Average Metric: 144.00 / 147 (98.0%):  77%|███████▋  | 147/192 [01:03<00:20,  2.16it/s]Validation Reasoning:
NO

Average Metric: 144.00 / 148 (97.3%):  77%|███████▋  | 148/192 [01:03<00:18,  2.44it/s]Validation Reasoning:
YES

Average Metric: 145.00 / 149 (97.3%):  78%|███████▊  | 149/192 [01:03<00:18,  2.27it/s]Validation Reasoning:
NO

Average Metric: 145.00 / 150 (96.7%):  78%|███████▊  | 150/192 [01:04<00:19,  2.15it/s]Validation Reasoning:
YES

Average Metric: 146.00 / 151 (96.7%):  79%|███████▊  | 151/192 [01:04<00:18,  2.22it/s]Validation Reasoning:
YES

Average Metric: 147.00 / 152 (96.7%):  79%|███████▉  | 152/192 [01:05<00:16,  2.43it/s]Validation Reasoning:
YES

Average Metric: 148.00 / 153 (96.7%):  80%|███████▉  | 153/192 [01:05<00:14,  2.76it/s]Validation Reasoning:
YES

Average Metric: 149.00 / 154 (96.8%):  80%|████████  | 154/192 [01:05<00:15,  2.52it/s]Validation Reasoning:
YES

Average Metric: 150.00 / 155 (96.8%):  81%|████████  | 155/192 [01:06<00:11,  3.21it/s]Validation Reasoning:
NO

Average Metric: 150.00 / 156 (96.2%):  81%|████████▏ | 156/192 [01:06<00:12,  2.84it/s]Validation Reasoning:
YES

Average Metric: 151.00 / 157 (96.2%):  82%|████████▏ | 157/192 [01:06<00:12,  2.80it/s]Validation Reasoning:
YES

Average Metric: 152.00 / 158 (96.2%):  82%|████████▏ | 158/192 [01:07<00:12,  2.74it/s]Validation Reasoning:
YES

Average Metric: 153.00 / 159 (96.2%):  83%|████████▎ | 159/192 [01:07<00:09,  3.32it/s]Validation Reasoning:
YES

Average Metric: 154.00 / 160 (96.2%):  83%|████████▎ | 160/192 [01:07<00:10,  3.19it/s]Validation Reasoning:
YES

Average Metric: 155.00 / 161 (96.3%):  84%|████████▍ | 161/192 [01:08<00:10,  2.97it/s]Validation Reasoning:
YES

Average Metric: 156.00 / 162 (96.3%):  84%|████████▍ | 162/192 [01:08<00:12,  2.41it/s]Validation Reasoning:
YES

Average Metric: 157.00 / 163 (96.3%):  85%|████████▍ | 163/192 [01:09<00:11,  2.48it/s]Validation Reasoning:
YES

Average Metric: 158.00 / 164 (96.3%):  85%|████████▌ | 164/192 [01:09<00:09,  3.07it/s]Validation Reasoning:
YES

Average Metric: 159.00 / 165 (96.4%):  85%|████████▌ | 164/192 [01:09<00:09,  3.07it/s]Validation Reasoning:
YES

Average Metric: 160.00 / 166 (96.4%):  86%|████████▋ | 166/192 [01:09<00:05,  4.61it/s]Validation Reasoning:
YES

Average Metric: 161.00 / 167 (96.4%):  87%|████████▋ | 167/192 [01:10<00:07,  3.25it/s]Validation Reasoning:
YES

Average Metric: 162.00 / 168 (96.4%):  88%|████████▊ | 168/192 [01:10<00:06,  3.45it/s]Validation Reasoning:
YES

Average Metric: 163.00 / 169 (96.4%):  88%|████████▊ | 169/192 [01:11<00:11,  2.03it/s]Validation Reasoning:
YES

Average Metric: 164.00 / 170 (96.5%):  88%|████████▊ | 169/192 [01:11<00:11,  2.03it/s]Validation Reasoning:
YES

Average Metric: 165.00 / 171 (96.5%):  89%|████████▉ | 171/192 [01:11<00:08,  2.38it/s]Validation Reasoning:
YES

Average Metric: 166.00 / 172 (96.5%):  90%|████████▉ | 172/192 [01:12<00:07,  2.63it/s]Validation Reasoning:
YES

Average Metric: 167.00 / 173 (96.5%):  90%|█████████ | 173/192 [01:12<00:06,  3.08it/s]Validation Reasoning:
YES

Average Metric: 168.00 / 174 (96.6%):  90%|█████████ | 173/192 [01:12<00:06,  3.08it/s]Validation Reasoning:
YES

Average Metric: 169.00 / 175 (96.6%):  91%|█████████ | 175/192 [01:13<00:07,  2.18it/s]Validation Reasoning:
YES

Average Metric: 170.00 / 176 (96.6%):  92%|█████████▏| 176/192 [01:14<00:08,  1.84it/s]Validation Reasoning:
YES

Average Metric: 171.00 / 177 (96.6%):  92%|█████████▏| 176/192 [01:14<00:08,  1.84it/s]Validation Reasoning:
YES


2025/05/01 02:16:35 INFO dspy.evaluate.evaluate: Average Metric: 185 / 192 (96.4%)

New best score: 96.35 for seed 2
Scores so far: [57.29, 94.27, 95.83, 90.1, 93.23, 96.35]
Best score so far: 96.35

  1%|          | 1/192 [00:03<12:23,  3.89s/it]

Validation Reasoning:
YES

  1%|          | 2/192 [00:07<11:30,  3.63s/it]

Validation Reasoning:
YES

Bootstrapped 2 full traces after 2 examples for up to 1 rounds, amounting to 2 attempts.
  0%|          | 0/192 [00:00<?, ?it/s]Validation Reasoning:
YES

Average Metric: 1.00 / 1 (100.0%):   1%|          | 1/192 [00:04<12:51,  4.04s/it]Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   1%|          | 2/192 [00:04<05:31,  1.74s/it]Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   1%|          | 2/192 [00:04<05:31,  1.74s/it]Validation Reasoning:
YES

Average Metric: 4.00 / 4 (100.0%):   2%|▏         | 4/192 [00:04<02:14,  1.39it/s]Validation Reasoning:
YES

Average Metric: 5.00 / 5 (100.0%):   3%|▎         | 5/192 [00:04<01:39,  1.88it/s]Validation Reasoning:
YES

Average Metric: 6.00 / 6 (100.0%):   3%|▎         | 6/192 [00:04<01:22,  2.25it/s]Validation Reasoning:
YES

Average Metric: 7.00 / 7 (100.0%):   4%|▎         | 7/192 [00:05<01:38,  1.87it/s]Validation Reasoning:
YES

Average Metric: 8.00 / 8 (100.0%):   4%|▍         | 8/192 [00:06<02:27,  1.25it/s]Validation Reasoning:
YES

Average Metric: 9.00 / 9 (100.0%):   5%|▍         | 9/192 [00:08<02:43,  1.12it/s]Validation Reasoning:
YES

Average Metric: 10.00 / 10 (100.0%):   5%|▌         | 10/192 [00:08<02:17,  1.32it/s]Validation Reasoning:
YES

Average Metric: 11.00 / 11 (100.0%):   6%|▌         | 11/192 [00:08<01:41,  1.78it/s]Validation Reasoning:
YES

Average Metric: 12.00 / 12 (100.0%):   6%|▌         | 11/192 [00:08<01:41,  1.78it/s]Validation Reasoning:
YES

Average Metric: 13.00 / 13 (100.0%):   7%|▋         | 13/192 [00:08<01:07,  2.65it/s]Validation Reasoning:
YES

Average Metric: 14.00 / 14 (100.0%):   7%|▋         | 13/192 [00:08<01:07,  2.65it/s]Validation Reasoning:
YES

Average Metric: 15.00 / 15 (100.0%):   8%|▊         | 15/192 [03:57<2:14:39, 45.65s/it]Validation Reasoning:
YES

Average Metric: 16.00 / 16 (100.0%):   8%|▊         | 16/192 [04:00<1:46:03, 36.16s/it]Validation Reasoning:
YES

Average Metric: 17.00 / 17 (100.0%):   9%|▉         | 17/192 [04:00<1:20:47, 27.70s/it]Validation Reasoning:
YES

Average Metric: 18.00 / 18 (100.0%):   9%|▉         | 18/192 [04:03<1:01:41, 21.27s/it]Validation Reasoning:
YES

Average Metric: 19.00 / 19 (100.0%):  10%|▉         | 19/192 [04:04<46:05, 15.99s/it]  Validation Reasoning:
YES

Average Metric: 20.00 / 20 (100.0%):  10%|█         | 20/192 [04:07<35:17, 12.31s/it]Validation Reasoning:
YES

Average Metric: 21.00 / 21 (100.0%):  11%|█         | 21/192 [04:12<28:59, 10.17s/it]Validation Reasoning:
YES

Average Metric: 22.00 / 22 (100.0%):  11%|█▏        | 22/192 [04:15<23:07,  8.16s/it]Validation Reasoning:
YES

Average Metric: 23.00 / 23 (100.0%):  12%|█▏        | 23/192 [04:18<18:21,  6.52s/it]Validation Reasoning:
YES

Average Metric: 24.00 / 24 (100.0%):  12%|█▎        | 24/192 [04:21<15:40,  5.60s/it]Validation Reasoning:
YES

Average Metric: 25.00 / 25 (100.0%):  13%|█▎        | 25/192 [04:22<11:46,  4.23s/it]Validation Reasoning:
YES

Average Metric: 26.00 / 26 (100.0%):  14%|█▎        | 26/192 [04:24<10:12,  3.69s/it]Validation Reasoning:
YES

Average Metric: 27.00 / 27 (100.0%):  14%|█▍        | 27/192 [04:26<08:18,  3.02s/it]Validation Reasoning:
YES

Average Metric: 28.00 / 28 (100.0%):  15%|█▍        | 28/192 [04:30<09:02,  3.31s/it]Validation Reasoning:
YES

Average Metric: 29.00 / 29 (100.0%):  15%|█▌        | 29/192 [04:33<08:50,  3.26s/it]Validation Reasoning:
YES

Average Metric: 30.00 / 30 (100.0%):  16%|█▌        | 30/192 [04:33<06:29,  2.41s/it]Validation Reasoning:
YES

Average Metric: 31.00 / 31 (100.0%):  16%|█▌        | 31/192 [04:37<07:23,  2.75s/it]Validation Reasoning:
YES

Average Metric: 32.00 / 32 (100.0%):  17%|█▋        | 32/192 [04:37<05:13,  1.96s/it]Validation Reasoning:
NO

Average Metric: 32.00 / 33 (97.0%):  17%|█▋        | 33/192 [04:42<07:13,  2.73s/it] Validation Reasoning:
YES

Average Metric: 33.00 / 34 (97.1%):  18%|█▊        | 34/192 [04:44<06:37,  2.52s/it]Validation Reasoning:
YES

Average Metric: 34.00 / 35 (97.1%):  18%|█▊        | 35/192 [04:46<06:49,  2.61s/it]Validation Reasoning:
YES

Average Metric: 35.00 / 36 (97.2%):  19%|█▉        | 36/192 [04:47<05:13,  2.01s/it]Validation Reasoning:
YES

Average Metric: 36.00 / 37 (97.3%):  19%|█▉        | 37/192 [04:53<08:30,  3.29s/it]Validation Reasoning:
YES

Average Metric: 37.00 / 38 (97.4%):  20%|█▉        | 38/192 [04:56<07:59,  3.11s/it]Validation Reasoning:
YES

Average Metric: 38.00 / 39 (97.4%):  20%|██        | 39/192 [04:57<06:33,  2.57s/it]Validation Reasoning:
YES

Average Metric: 39.00 / 40 (97.5%):  21%|██        | 40/192 [05:00<06:35,  2.60s/it]Validation Reasoning:
YES

Average Metric: 40.00 / 41 (97.6%):  21%|██▏       | 41/192 [05:01<05:15,  2.09s/it]Validation Reasoning:
YES

Average Metric: 41.00 / 42 (97.6%):  22%|██▏       | 42/192 [05:05<06:31,  2.61s/it]Validation Reasoning:
YES

Average Metric: 42.00 / 43 (97.7%):  22%|██▏       | 43/192 [05:05<04:43,  1.90s/it]Validation Reasoning:
YES

Average Metric: 43.00 / 44 (97.7%):  23%|██▎       | 44/192 [05:08<05:09,  2.09s/it]Validation Reasoning:
YES

Average Metric: 44.00 / 45 (97.8%):  23%|██▎       | 45/192 [05:08<04:07,  1.68s/it]Validation Reasoning:
YES

Average Metric: 45.00 / 46 (97.8%):  24%|██▍       | 46/192 [05:12<05:40,  2.33s/it]Validation Reasoning:
YES

Average Metric: 46.00 / 47 (97.9%):  24%|██▍       | 46/192 [05:12<05:40,  2.33s/it]Validation Reasoning:
YES

Average Metric: 47.00 / 48 (97.9%):  25%|██▌       | 48/192 [05:16<04:56,  2.06s/it]Validation Reasoning:
NO

Average Metric: 47.00 / 49 (95.9%):  26%|██▌       | 49/192 [05:23<07:54,  3.32s/it]Validation Reasoning:
YES

Average Metric: 48.00 / 50 (96.0%):  26%|██▌       | 50/192 [05:23<05:54,  2.49s/it]Validation Reasoning:
YES

Average Metric: 49.00 / 51 (96.1%):  27%|██▋       | 51/192 [05:27<06:37,  2.82s/it]Validation Reasoning:
YES

Average Metric: 50.00 / 52 (96.2%):  27%|██▋       | 52/192 [05:27<05:03,  2.17s/it]Validation Reasoning:
YES

Average Metric: 51.00 / 53 (96.2%):  28%|██▊       | 53/192 [05:30<05:43,  2.47s/it]Validation Reasoning:
YES

Average Metric: 52.00 / 54 (96.3%):  28%|██▊       | 54/192 [05:32<05:00,  2.18s/it]Validation Reasoning:
YES

Average Metric: 53.00 / 55 (96.4%):  29%|██▊       | 55/192 [05:34<05:17,  2.32s/it]Validation Reasoning:
YES

Average Metric: 54.00 / 56 (96.4%):  29%|██▉       | 56/192 [05:36<04:31,  2.00s/it]Validation Reasoning:
NO

Average Metric: 54.00 / 57 (94.7%):  30%|██▉       | 57/192 [05:38<04:40,  2.08s/it]Validation Reasoning:
YES

Average Metric: 55.00 / 58 (94.8%):  30%|███       | 58/192 [05:39<04:16,  1.91s/it]Validation Reasoning:
YES

Average Metric: 56.00 / 59 (94.9%):  31%|███       | 59/192 [05:42<04:30,  2.03s/it]Validation Reasoning:
YES

Average Metric: 57.00 / 60 (95.0%):  31%|███▏      | 60/192 [05:43<03:52,  1.76s/it]Validation Reasoning:
YES

Average Metric: 58.00 / 61 (95.1%):  32%|███▏      | 61/192 [05:49<06:57,  3.19s/it]Validation Reasoning:
YES

Average Metric: 59.00 / 62 (95.2%):  32%|███▏      | 62/192 [05:51<05:56,  2.74s/it]Validation Reasoning:
YES

Average Metric: 60.00 / 63 (95.2%):  33%|███▎      | 63/192 [05:53<05:28,  2.55s/it]Validation Reasoning:
YES

Average Metric: 61.00 / 64 (95.3%):  33%|███▎      | 64/192 [05:57<06:26,  3.02s/it]Validation Reasoning:
YES

Average Metric: 62.00 / 65 (95.4%):  34%|███▍      | 65/192 [06:00<06:11,  2.93s/it]Validation Reasoning:
YES

Average Metric: 63.00 / 66 (95.5%):  34%|███▍      | 66/192 [06:01<04:53,  2.33s/it]Validation Reasoning:
YES

Average Metric: 64.00 / 67 (95.5%):  35%|███▍      | 67/192 [06:04<05:30,  2.65s/it]Validation Reasoning:
YES

Average Metric: 65.00 / 68 (95.6%):  35%|███▌      | 68/192 [06:06<05:01,  2.43s/it]Validation Reasoning:
YES

Average Metric: 66.00 / 69 (95.7%):  36%|███▌      | 69/192 [06:09<05:22,  2.62s/it]Validation Reasoning:
YES

Average Metric: 67.00 / 70 (95.7%):  36%|███▋      | 70/192 [06:10<04:25,  2.18s/it]Validation Reasoning:
YES

Average Metric: 68.00 / 71 (95.8%):  37%|███▋      | 71/192 [06:13<04:45,  2.36s/it]Validation Reasoning:
YES

Average Metric: 69.00 / 72 (95.8%):  38%|███▊      | 72/192 [06:17<05:14,  2.62s/it]Validation Reasoning:
YES

Average Metric: 70.00 / 73 (95.9%):  38%|███▊      | 73/192 [06:17<04:06,  2.07s/it]Validation Reasoning:
YES

Average Metric: 71.00 / 74 (95.9%):  39%|███▊      | 74/192 [06:20<04:36,  2.35s/it]Validation Reasoning:
YES

Average Metric: 72.00 / 75 (96.0%):  39%|███▉      | 75/192 [06:22<04:06,  2.11s/it]Validation Reasoning:
YES

Average Metric: 73.00 / 76 (96.1%):  40%|███▉      | 76/192 [06:24<03:52,  2.00s/it]Validation Reasoning:
YES

Average Metric: 74.00 / 77 (96.1%):  40%|████      | 77/192 [06:26<03:58,  2.08s/it]Validation Reasoning:
YES

Average Metric: 75.00 / 78 (96.2%):  41%|████      | 78/192 [06:28<04:06,  2.16s/it]Validation Reasoning:
YES

Average Metric: 76.00 / 79 (96.2%):  41%|████      | 79/192 [06:30<03:46,  2.00s/it]Validation Reasoning:
YES

Average Metric: 77.00 / 80 (96.2%):  42%|████▏     | 80/192 [06:34<04:54,  2.63s/it]Validation Reasoning:
YES

Average Metric: 78.00 / 81 (96.3%):  42%|████▏     | 81/192 [06:38<05:34,  3.01s/it]Validation Reasoning:
YES

Average Metric: 79.00 / 82 (96.3%):  43%|████▎     | 82/192 [06:39<04:45,  2.60s/it]Validation Reasoning:
YES

Average Metric: 80.00 / 83 (96.4%):  43%|████▎     | 83/192 [06:42<04:31,  2.49s/it]Validation Reasoning:
YES

Average Metric: 81.00 / 84 (96.4%):  44%|████▍     | 84/192 [06:43<04:01,  2.24s/it]Validation Reasoning:
YES

Average Metric: 82.00 / 85 (96.5%):  44%|████▍     | 85/192 [06:46<04:03,  2.27s/it]Validation Reasoning:
YES

Average Metric: 83.00 / 86 (96.5%):  45%|████▍     | 86/192 [06:47<03:31,  1.99s/it]Validation Reasoning:
YES

Average Metric: 84.00 / 87 (96.6%):  45%|████▌     | 87/192 [06:50<03:45,  2.15s/it]Validation Reasoning:
YES

Average Metric: 85.00 / 88 (96.6%):  46%|████▌     | 88/192 [06:51<03:25,  1.98s/it]Validation Reasoning:
YES

Average Metric: 86.00 / 89 (96.6%):  46%|████▋     | 89/192 [06:53<03:12,  1.87s/it]Validation Reasoning:
YES

Average Metric: 87.00 / 90 (96.7%):  47%|████▋     | 90/192 [06:55<03:35,  2.11s/it]Validation Reasoning:
YES

Average Metric: 88.00 / 91 (96.7%):  47%|████▋     | 91/192 [06:57<03:06,  1.84s/it]Validation Reasoning:
YES

Average Metric: 89.00 / 92 (96.7%):  48%|████▊     | 92/192 [06:59<03:10,  1.91s/it]Validation Reasoning:
YES

Average Metric: 90.00 / 93 (96.8%):  48%|████▊     | 93/192 [07:00<02:45,  1.67s/it]Validation Reasoning:
YES

Average Metric: 91.00 / 94 (96.8%):  49%|████▉     | 94/192 [07:02<03:11,  1.96s/it]Validation Reasoning:
YES

Average Metric: 92.00 / 95 (96.8%):  49%|████▉     | 95/192 [07:06<04:07,  2.55s/it]Validation Reasoning:
YES

Average Metric: 93.00 / 96 (96.9%):  50%|█████     | 96/192 [07:08<03:26,  2.16s/it]Validation Reasoning:
YES

Average Metric: 94.00 / 97 (96.9%):  51%|█████     | 97/192 [07:10<03:43,  2.35s/it]Validation Reasoning:
YES

Average Metric: 95.00 / 98 (96.9%):  51%|█████     | 98/192 [07:11<02:40,  1.71s/it]Validation Reasoning:
YES

Average Metric: 96.00 / 99 (97.0%):  52%|█████▏    | 99/192 [07:14<03:32,  2.29s/it]Validation Reasoning:
YES

Average Metric: 97.00 / 100 (97.0%):  52%|█████▏    | 100/192 [07:14<02:32,  1.66s/it]Validation Reasoning:
YES

Average Metric: 98.00 / 101 (97.0%):  53%|█████▎    | 101/192 [07:18<03:15,  2.15s/it]Validation Reasoning:
YES

Average Metric: 99.00 / 102 (97.1%):  53%|█████▎    | 102/192 [07:18<02:26,  1.63s/it]Validation Reasoning:
YES

Average Metric: 100.00 / 103 (97.1%):  54%|█████▎    | 103/192 [07:22<03:27,  2.33s/it]Validation Reasoning:
YES

Average Metric: 101.00 / 104 (97.1%):  54%|█████▍    | 104/192 [07:24<03:12,  2.19s/it]Validation Reasoning:
YES

Average Metric: 102.00 / 105 (97.1%):  55%|█████▍    | 105/192 [07:26<03:04,  2.12s/it]Validation Reasoning:
YES

Average Metric: 103.00 / 106 (97.2%):  55%|█████▌    | 106/192 [07:28<02:58,  2.08s/it]Validation Reasoning:
YES

Average Metric: 104.00 / 107 (97.2%):  56%|█████▌    | 107/192 [07:30<02:46,  1.96s/it]Validation Reasoning:
YES

Average Metric: 105.00 / 108 (97.2%):  56%|█████▌    | 107/192 [07:32<02:46,  1.96s/it]Validation Reasoning:
YES
Average Metric: 105.00 / 108 (97.2%):  56%|█████▋    | 108/192 [07:32<03:05,  2.21s/it]
Average Metric: 106.00 / 109 (97.2%):  56%|█████▋    | 108/192 [07:32<03:05,  2.21s/it]Validation Reasoning:
YES

Average Metric: 107.00 / 110 (97.3%):  57%|█████▋    | 110/192 [07:34<02:08,  1.57s/it]Validation Reasoning:
YES

Average Metric: 108.00 / 111 (97.3%):  58%|█████▊    | 111/192 [07:36<02:19,  1.72s/it]Validation Reasoning:
YES

Average Metric: 109.00 / 112 (97.3%):  58%|█████▊    | 112/192 [07:38<02:17,  1.72s/it]Validation Reasoning:
YES

Average Metric: 110.00 / 113 (97.3%):  59%|█████▉    | 113/192 [07:40<02:15,  1.72s/it]Validation Reasoning:
YES

Average Metric: 111.00 / 114 (97.4%):  59%|█████▉    | 114/192 [07:42<02:19,  1.79s/it]Validation Reasoning:
YES

Average Metric: 112.00 / 115 (97.4%):  60%|█████▉    | 115/192 [07:44<02:29,  1.94s/it]Validation Reasoning:
YES

Average Metric: 113.00 / 116 (97.4%):  60%|██████    | 116/192 [07:46<02:34,  2.03s/it]Validation Reasoning:
YES

Average Metric: 114.00 / 117 (97.4%):  61%|██████    | 117/192 [07:48<02:30,  2.01s/it]Validation Reasoning:
YES

Average Metric: 115.00 / 118 (97.5%):  61%|██████▏   | 118/192 [07:51<02:47,  2.26s/it]Validation Reasoning:
YES

Average Metric: 116.00 / 119 (97.5%):  62%|██████▏   | 119/192 [07:51<02:00,  1.65s/it]Validation Reasoning:
YES

Average Metric: 117.00 / 120 (97.5%):  62%|██████▎   | 120/192 [07:54<02:30,  2.09s/it]Validation Reasoning:
YES

Average Metric: 118.00 / 121 (97.5%):  63%|██████▎   | 121/192 [07:55<02:07,  1.79s/it]Validation Reasoning:
YES

Average Metric: 119.00 / 122 (97.5%):  63%|██████▎   | 121/192 [08:00<02:07,  1.79s/it]Validation Reasoning:
YES

Average Metric: 120.00 / 123 (97.6%):  64%|██████▍   | 123/192 [08:00<02:06,  1.83s/it]Validation Reasoning:
YES

Average Metric: 121.00 / 124 (97.6%):  65%|██████▍   | 124/192 [08:03<02:39,  2.34s/it]Validation Reasoning:
NO

Average Metric: 121.00 / 125 (96.8%):  65%|██████▌   | 125/192 [08:04<01:59,  1.79s/it]Validation Reasoning:
YES

Average Metric: 122.00 / 126 (96.8%):  66%|██████▌   | 126/192 [08:07<02:29,  2.27s/it]Validation Reasoning:
YES

Average Metric: 123.00 / 127 (96.9%):  66%|██████▌   | 127/192 [08:08<01:46,  1.65s/it]Validation Reasoning:
YES

Average Metric: 124.00 / 128 (96.9%):  67%|██████▋   | 128/192 [08:12<02:31,  2.37s/it]Validation Reasoning:
YES

Average Metric: 125.00 / 129 (96.9%):  67%|██████▋   | 129/192 [08:12<01:50,  1.75s/it]Validation Reasoning:
YES

Average Metric: 126.00 / 130 (96.9%):  68%|██████▊   | 130/192 [08:15<02:10,  2.10s/it]Validation Reasoning:
YES

Average Metric: 127.00 / 131 (96.9%):  68%|██████▊   | 131/192 [08:16<01:47,  1.76s/it]Validation Reasoning:
NO

Average Metric: 127.00 / 132 (96.2%):  69%|██████▉   | 132/192 [08:19<02:19,  2.33s/it]Validation Reasoning:
YES

Average Metric: 128.00 / 133 (96.2%):  69%|██████▉   | 133/192 [08:20<01:51,  1.88s/it]Validation Reasoning:
YES

Average Metric: 129.00 / 134 (96.3%):  70%|██████▉   | 134/192 [08:23<01:55,  2.00s/it]Validation Reasoning:
YES

Average Metric: 130.00 / 135 (96.3%):  70%|███████   | 135/192 [08:25<02:01,  2.14s/it]Validation Reasoning:
YES

Average Metric: 131.00 / 136 (96.3%):  71%|███████   | 136/192 [08:27<01:54,  2.04s/it]Validation Reasoning:
YES

Average Metric: 132.00 / 137 (96.4%):  71%|███████▏  | 137/192 [08:29<01:53,  2.06s/it]Validation Reasoning:
YES

Average Metric: 133.00 / 138 (96.4%):  72%|███████▏  | 138/192 [08:30<01:39,  1.85s/it]Validation Reasoning:
YES

Average Metric: 134.00 / 139 (96.4%):  72%|███████▏  | 139/192 [08:33<01:55,  2.18s/it]Validation Reasoning:
YES

Average Metric: 135.00 / 140 (96.4%):  73%|███████▎  | 140/192 [08:34<01:25,  1.65s/it]Validation Reasoning:
YES

Average Metric: 136.00 / 141 (96.5%):  73%|███████▎  | 141/192 [08:37<01:47,  2.11s/it]Validation Reasoning:
NO

Average Metric: 136.00 / 142 (95.8%):  74%|███████▍  | 142/192 [08:38<01:30,  1.81s/it]Validation Reasoning:
YES

Average Metric: 137.00 / 143 (95.8%):  74%|███████▍  | 143/192 [08:41<01:46,  2.17s/it]Validation Reasoning:
YES

Average Metric: 138.00 / 144 (95.8%):  75%|███████▌  | 144/192 [08:43<01:36,  2.01s/it]Validation Reasoning:
YES

Average Metric: 139.00 / 145 (95.9%):  76%|███████▌  | 145/192 [08:45<01:44,  2.23s/it]Validation Reasoning:
YES

Average Metric: 140.00 / 146 (95.9%):  76%|███████▌  | 146/192 [08:46<01:24,  1.84s/it]Validation Reasoning:
YES

Average Metric: 141.00 / 147 (95.9%):  77%|███████▋  | 147/192 [08:49<01:34,  2.11s/it]Validation Reasoning:
YES

Average Metric: 142.00 / 148 (95.9%):  77%|███████▋  | 148/192 [08:51<01:37,  2.21s/it]Validation Reasoning:
NO

Average Metric: 142.00 / 149 (95.3%):  78%|███████▊  | 149/192 [08:52<01:14,  1.74s/it]Validation Reasoning:
YES

Average Metric: 143.00 / 150 (95.3%):  78%|███████▊  | 150/192 [08:55<01:31,  2.17s/it]Validation Reasoning:
YES

Average Metric: 144.00 / 151 (95.4%):  79%|███████▊  | 151/192 [08:56<01:12,  1.77s/it]Validation Reasoning:
YES

Average Metric: 145.00 / 152 (95.4%):  79%|███████▉  | 152/192 [09:01<01:42,  2.56s/it]Validation Reasoning:
YES

Average Metric: 146.00 / 153 (95.4%):  80%|███████▉  | 153/192 [09:01<01:11,  1.83s/it]Validation Reasoning:
YES

Average Metric: 147.00 / 154 (95.5%):  80%|████████  | 154/192 [09:04<01:28,  2.34s/it]Validation Reasoning:
YES

Average Metric: 148.00 / 155 (95.5%):  81%|████████  | 155/192 [09:04<01:02,  1.70s/it]Validation Reasoning:
YES

Average Metric: 149.00 / 156 (95.5%):  81%|████████▏ | 156/192 [09:08<01:26,  2.41s/it]Validation Reasoning:
YES

Average Metric: 150.00 / 157 (95.5%):  81%|████████▏ | 156/192 [09:08<01:26,  2.41s/it]Validation Reasoning:
YES

Average Metric: 151.00 / 158 (95.6%):  82%|████████▏ | 158/192 [09:14<01:26,  2.54s/it]Validation Reasoning:
YES

Average Metric: 152.00 / 159 (95.6%):  83%|████████▎ | 159/192 [09:14<01:04,  1.97s/it]Validation Reasoning:
YES

Average Metric: 153.00 / 160 (95.6%):  83%|████████▎ | 160/192 [09:18<01:16,  2.38s/it]Validation Reasoning:
YES

Average Metric: 154.00 / 161 (95.7%):  84%|████████▍ | 161/192 [09:18<01:00,  1.95s/it]Validation Reasoning:
YES

Average Metric: 155.00 / 162 (95.7%):  84%|████████▍ | 162/192 [09:22<01:11,  2.37s/it]Validation Reasoning:
YES

Average Metric: 156.00 / 163 (95.7%):  85%|████████▍ | 163/192 [09:22<00:52,  1.82s/it]Validation Reasoning:
YES

Average Metric: 157.00 / 164 (95.7%):  85%|████████▌ | 164/192 [09:26<01:02,  2.24s/it]Validation Reasoning:
YES

Average Metric: 158.00 / 165 (95.8%):  86%|████████▌ | 165/192 [09:26<00:47,  1.74s/it]Validation Reasoning:
YES

Average Metric: 159.00 / 166 (95.8%):  86%|████████▋ | 166/192 [09:29<00:56,  2.16s/it]Validation Reasoning:
YES

Average Metric: 160.00 / 167 (95.8%):  87%|████████▋ | 167/192 [09:31<00:50,  2.00s/it]Validation Reasoning:
YES

Average Metric: 161.00 / 168 (95.8%):  88%|████████▊ | 168/192 [09:33<00:47,  2.00s/it]Validation Reasoning:
YES

Average Metric: 162.00 / 169 (95.9%):  88%|████████▊ | 169/192 [09:34<00:43,  1.89s/it]Validation Reasoning:
YES

Average Metric: 163.00 / 170 (95.9%):  89%|████████▊ | 170/192 [09:36<00:41,  1.87s/it]Validation Reasoning:
YES

Average Metric: 164.00 / 171 (95.9%):  89%|████████▉ | 171/192 [09:39<00:47,  2.25s/it]Validation Reasoning:
NO

Average Metric: 164.00 / 172 (95.3%):  90%|████████▉ | 172/192 [09:40<00:34,  1.71s/it]Validation Reasoning:
YES

Average Metric: 165.00 / 173 (95.4%):  90%|█████████ | 173/192 [09:43<00:43,  2.28s/it]Validation Reasoning:
YES

Average Metric: 166.00 / 174 (95.4%):  91%|█████████ | 174/192 [09:45<00:37,  2.11s/it]Validation Reasoning:
YES

Average Metric: 167.00 / 175 (95.4%):  91%|█████████ | 175/192 [09:47<00:36,  2.15s/it]Validation Reasoning:
YES


2025/05/01 02:30:41 INFO dspy.evaluate.evaluate: Average Metric: 184 / 192 (95.8%)

Scores so far: [57.29, 94.27, 95.83, 90.1, 93.23, 96.35, 95.83]
Best score so far: 96.35
7 candidate programs found.

Validation Reasoning:
YES

In [119]:
evaluator(compiled_pred)

  0%|          | 0/22 [00:00<?, ?it/s]Validation Reasoning:
YES

Average Metric: 1.00 / 1 (100.0%):   5%|▍         | 1/22 [00:04<01:27,  4.17s/it]Validation Reasoning:
YES

Average Metric: 2.00 / 2 (100.0%):   9%|▉         | 2/22 [00:04<00:35,  1.79s/it]Validation Reasoning:
YES

Average Metric: 3.00 / 3 (100.0%):   9%|▉         | 2/22 [00:04<00:35,  1.79s/it]Validation Reasoning:
NO

Average Metric: 3.00 / 4 (75.0%):  14%|█▎        | 3/22 [00:04<00:20,  1.07s/it] Validation Reasoning:
YES

Average Metric: 4.00 / 5 (80.0%):  23%|██▎       | 5/22 [00:04<00:08,  1.96it/s]Validation Reasoning:
YES

Average Metric: 5.00 / 6 (83.3%):  27%|██▋       | 6/22 [00:07<00:19,  1.19s/it]Validation Reasoning:
YES

Average Metric: 6.00 / 7 (85.7%):  27%|██▋       | 6/22 [00:07<00:19,  1.19s/it]Validation Reasoning:
YES
Average Metric: 6.00 / 7 (85.7%):  32%|███▏      | 7/22 [00:07<00:14,  1.05it/s]
Average Metric: 7.00 / 8 (87.5%):  36%|███▋      | 8/22 [00:08<00:10,  1.38it/s]Validation Reasoning:
YES

Average Metric: 8.00 / 9 (88.9%):  41%|████      | 9/22 [00:10<00:14,  1.14s/it]Validation Reasoning:
YES

Average Metric: 9.00 / 10 (90.0%):  45%|████▌     | 10/22 [00:11<00:13,  1.16s/it]Validation Reasoning:
NO

Average Metric: 9.00 / 11 (81.8%):  45%|████▌     | 10/22 [00:11<00:13,  1.16s/it]Validation Reasoning:
YES

Average Metric: 10.00 / 12 (83.3%):  55%|█████▍    | 12/22 [00:12<00:09,  1.02it/s]Validation Reasoning:
YES

Average Metric: 11.00 / 13 (84.6%):  59%|█████▉    | 13/22 [00:14<00:10,  1.17s/it]Validation Reasoning:
YES

Average Metric: 12.00 / 14 (85.7%):  64%|██████▎   | 14/22 [00:15<00:09,  1.13s/it]Validation Reasoning:
YES

Average Metric: 13.00 / 15 (86.7%):  64%|██████▎   | 14/22 [00:15<00:09,  1.13s/it]Validation Reasoning:
YES

Average Metric: 14.00 / 16 (87.5%):  73%|███████▎  | 16/22 [00:17<00:06,  1.09s/it]Validation Reasoning:
YES

Average Metric: 15.00 / 17 (88.2%):  73%|███████▎  | 16/22 [00:18<00:06,  1.09s/it]Validation Reasoning:
YES
Average Metric: 15.00 / 17 (88.2%):  77%|███████▋  | 17/22 [00:18<00:05,  1.06s/it]
Average Metric: 16.00 / 18 (88.9%):  77%|███████▋  | 17/22 [00:18<00:05,  1.06s/it]Validation Reasoning:
YES

Average Metric: 17.00 / 19 (89.5%):  86%|████████▋ | 19/22 [00:18<00:02,  1.48it/s]Validation Reasoning:
YES

Average Metric: 18.00 / 20 (90.0%):  91%|█████████ | 20/22 [00:20<00:01,  1.06it/s]Validation Reasoning:
YES

Average Metric: 19.00 / 21 (90.5%):  95%|█████████▌| 21/22 [00:21<00:00,  1.23it/s]Validation Reasoning:
YES

Average Metric: 20.00 / 22 (90.9%): 100%|██████████| 22/22 [00:21<00:00,  1.01it/s]

2025/05/01 02:31:03 INFO dspy.evaluate.evaluate: Average Metric: 20 / 22 (90.9%)

,natural_language_prompt,example_MacOS_shell_command,reasoning,pred_MacOS_shell_command,metric
0,Search for 'Deep Learning books' on Google using Safari,open -a Safari 'https://www.google.com/search?q=Deep+Learning+books',Not supplied for this particular example.,open -a Safari 'https://www.google.com/search?q=Deep+Learning+books',✔️ [1]
1,Create a new Python virtual environment,python3 -m venv myenv,Not supplied for this particular example.,python3 -m venv .venv,✔️ [1]
2,Check for system crashes,"log show --predicate 'eventMessage CONTAINS \crash\""' --style syslog""",Not supplied for this particular example.,"log show --predicate 'eventMessage CONTAINS ""panic""' --last 24h",
3,Can you explain the contents of the 'AI_Research_Projects' folder?,find ~/Documents/AI_Research_Projects -type f -exec cat {} ; | more,Not supplied for this particular example.,find ~/Documents/AI_Research_Projects -type f -exec cat {} ; | more,✔️ [1]
4,What's inside the 'Reinforcement_Learning_Projects' folder?,find ~/Documents/Reinforcement_Learning_Projects -type f -exec cat...,Not supplied for this particular example.,find ~/Documents/Reinforcement_Learning_Projects -type f -exec cat...,✔️ [1]
5,Search through the 'Deep_Learning' folder and summarize its content,find ~/Documents/Deep_Learning -type f -exec cat {} ; | more,Not supplied for this particular example.,find ~/Documents/Deep_Learning -type f -exec cat {} ; | more,✔️ [1]
6,Search for 'ensemble learning' in my Documents,find ~/Documents -type f -exec grep -i -E 'ensemble\s*learning' {} ;,Not supplied for this particular example.,find ~/Documents -type f -exec grep -i -E 'ensemble\s*learning|bag...,
7,Check the 'Research_Projects' folder for code using 'KNN',find ~/Documents/Research_Projects -type f -exec grep -i -E 'KNN|k...,Not supplied for this particular example.,find ~/Documents/Research_Projects -type f -exec grep -i 'KNN' {} \;,✔️ [1]
8,Could you explain the contents of 'ML_Research' folder?,find ~/Documents/ML_Research -type f -exec cat {} ; | more,Not supplied for this particular example.,find ~/Documents/ML_Research -type f -exec cat {} ; | more,✔️ [1]
9,Look for any project files mentioning 'support vector machine' in ...,find ~/Documents -type f -exec grep -i -E 'support\s*vector\s*mach...,Not supplied for this particular example.,find ~/Documents -type f -exec grep -i -E 'support\s*vector\s*mach...,✔️ [1]
10,Play 'Watermelon Sugar' on YouTube using Firefox,if command -v firefox >/dev/null 2>&1; then firefox 'https://www.y...,Not supplied for this particular example.,if command -v firefox >/dev/null 2>&1; then firefox 'https://www.y...,✔️ [1]
11,Look for code that uses OpenCV in the 'Computer_Vision' folder,find ~/Documents/Computer_Vision -type f -exec grep -i -E 'opencv|...,Not supplied for this particular example.,find ~/Documents/Computer_Vision -type f -exec grep -i -E 'import\...,✔️ [1]
12,What's inside the 'Text_Analysis_Projects' folder?,find ~/Documents/Text_Analysis_Projects -type f -exec cat {} ; | more,Not supplied for this particular example.,find ~/Documents/Text_Analysis_Projects -type f -exec cat {} ; | more,✔️ [1]
13,Search for 'AI applications in healthcare' on Google using Safari,open -a Safari 'https://www.google.com/search?q=AI+applications+in...,Not supplied for this particular example.,open -a Safari 'https://www.google.com/search?q=AI+applications+in...,✔️ [1]
14,Setup Python Django project with PostgreSQL,python3 -m venv venv && source venv/bin/activate && pip install dj...,Not supplied for this particular example.,python3 -m venv .venv && source .venv/bin/activate && pip install ...,✔️ [1]
15,Play 'Bad Guy' on YouTube using Firefox,if command -v firefox >/dev/null 2>&1; then firefox 'https://www.y...,Not supplied for this particular example.,if command -v firefox >/dev/null 2>&1; then firefox 'https://www.y...,✔️ [1]
16,Look inside the 'ML_Research' folder for code using PyTorch,find ~/Documents/ML_Research -type f -exec grep -i -E 'torch|pytor...,Not supplied for this particular example.,find ~/Documents/ML_Research -type f -exec grep -i -E 'import\s*to...,✔️ [1]
17,Find any research project in my Documents folder that talks about ...,find ~/Documents -type f -exec grep -i -E 'unsupervised\s*learning...,Not supplied for this particular example.,find ~/Documents -type f -exec grep -i -E 'unsupervised\s*learning...,✔️ [1]
18,Find all large files (>100MB) in Documents,find ~/Documents -type f -size +100M,Not supplied for this particular example.,find ~/Documents -type f -size +100M -exec ls -lh {} \;,✔️ [1]
19,Search for any code in 'Computer_Vision' related to 'object detect...,find ~/Documents/Computer_Vision -type f -exec grep -i -E 'object\...,Not supplied for this particular example.,find ~/Documents/Computer_Vision -type f -exec grep -i -E 'object\...,✔️ [1]
20,Play 'Levitating' on Spotify,if command -v spotify >/dev/null 2>&1; then spotify play 'Levitati...,Not supplied for this particular example.,if command -v spotify >/dev/null 2>&1; then spotify play 'Levitati...,✔️ [1]
21,Look for any projects in Documents related to 'feature selection',find ~/Documents -type f -exec grep -i -E 'feature\s*selection' {} ;,Not supplied for this particular example.,find ~/Documents -type f -exec grep -i -E 'feature\s*selection|fea...,✔️ [1]

90.91

In [120]:



import re

def clean_command(command):
    command = command.replace('bash', '')
    command = re.sub(r'\\', '', command)
    return command



def generateAndClean(prompt):
    extratced_command = compiled_pred(question=prompt).answer
    cleaned_command = clean_command(generator(question = f"Separate all the commands with a ; in this: {extratced_command} if each command has to be run sequentially").answer)
    return cleaned_command

print(generateAndClean("i wanna see last two login entreis in system logf file"))

TypeError: CommandGenerator.forward() got an unexpected keyword argument 'question'

In [121]:
current_directory = "/Users/nouman/Desktop/dspy_tutorials /saved_prorgam"

# Define the path for saving the model

# Save the generator model with the valid path
compiled_pred.save(current_directory,save_program=True)

In [ ]:
import subprocess

def execute_shell_command(natural_language_query, capture_output=False, check=False, shell=True):
    """
    Given a user's request in Natural Language generates and executes a shell command that may contain multiple lines, executing each line sequentially.

    Parameters:
        natural_language_query(str): User's request in a natural language

    Returns:
        list: A list of subprocess.CompletedProcess objects for each command executed.
    """
    # Extract command using your model (assuming compiled_pred works as expected)
    extratced_command = compiled_pred(question=natural_language_query).answer
    print(f"Extracted Command: {extratced_command}")

    # Split the command by newlines
    commands = extratced_command.splitlines()
    print(commands)

    results = []
    for cmd in commands:
        cmd = cmd.strip()  # Clean command
        
        if cmd:  # Ensure the command is not empty
            try:
                # If the command contains a multi-line input, handle it with echo and piping
                if '<<EOT' in cmd:
                    # Use echo and piping to execute multi-line heredoc commands
                    result = subprocess.run(f'echo "{cmd}" | bash', capture_output=capture_output, check=check, shell=True, text=True)
                else:
                    # Execute the command normally
                    result = subprocess.run(cmd, capture_output=capture_output, check=check, shell=shell, text=True)

                # Capture the result if output is needed
                if capture_output:
                    results.append(result.stdout)
                else:
                    results.append(result)
            except subprocess.CalledProcessError as e:
                print(f"Command '{e.cmd}' failed with exit code {e.returncode}")
                if capture_output:
                    print(f"Error output: {e.stderr}")
                else:
                    print(f"Error output: {e.output}")
                raise
            except FileNotFoundError as e:
                print(f"Command not found: {e.filename}")
                raise
            except Exception as e:
                print(f"An unexpected error occurred: {e}")
                raise

    # Return the final result or first result (as per your logic)
    return results[0].args if results else []

# Example usage
print(execute_shell_command(natural_language_query=" python proj folder with a venv folder and flask deps in req.txt file on dekspot"))

Extracted Command: mkdir -p ~/Desktop/python_proj/venv
python3 -m venv ~/Desktop/python_proj/venv
touch ~/Desktop/python_proj/requirements.txt
echo "Add Flask to requirements.txt, then activate the venv and run: pip install -r requirements.txt"
['mkdir -p ~/Desktop/python_proj/venv', 'python3 -m venv ~/Desktop/python_proj/venv', 'touch ~/Desktop/python_proj/requirements.txt', 'echo "Add Flask to requirements.txt, then activate the venv and run: pip install -r requirements.txt"']
Add Flask to requirements.txt, then activate the venv and run: pip install -r requirements.txt
mkdir -p ~/Desktop/python_proj/venv

In [ ]:
react = dspy.ReAct("natural_language_query -> execution_result", tools=[execute_shell_command])
pred = react(natural_language_query="flask folder on Desktop with starter code inside with at least 5 endpoints")
print(pred.execution_result)

Extracted Command: mkdir ~/Desktop/flask_app
['mkdir ~/Desktop/flask_app']
Extracted Command: ```bash
mkdir -p ~/Desktop/flask_app
```
['```bash', 'mkdir -p ~/Desktop/flask_app', '```']
Command '```bash' failed with exit code 2
Error output: /bin/sh: -c: line 0: unexpected EOF while looking for matching ``'
/bin/sh: -c: line 1: syntax error: unexpected end of file

I was not able to create the flask app due to repeated errors in executing the shell commands.